/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-10-27 04:49:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.rehearsal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.company.vo.CompanyVO;
import kr.or.ddit.cmm.util.SessionCheck;
import kr.or.ddit.member.vo.MemberVO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.cmm.util.SessionCheck");
    _jspx_imports_classes.add("kr.or.ddit.member.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.company.vo.CompanyVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int memCode = 0;
int memNo = 0;
int hrNo = 0;
int cnt = 0;
int comNo = 0;
MemberVO vo = new MemberVO();
CompanyVO cv = null;

String myProfileImg = "/CodePeople/images/helloHome.png";
String myPage = "";

if(SessionCheck.isLoginMember(session)){
   vo = (MemberVO) session.getAttribute("memVO");

 	memCode = 0; // 비회원
 	
 	if(vo.getMemIsApi() == 1){
 		myProfileImg = vo.getMemImgUrl();
 	}
	
	if(vo.getMemCode() == 1){				// 개인회원
		memCode = vo.getMemCode();
		myPage = "/CodePeople/mainJsp/myPagePerson.jsp";
	} else if (vo.getMemCode() == 2){		// 기업회원
		memCode = vo.getMemCode();
		myPage = "/CodePeople/rehearsal/myPageCompany.html";
	} else if(vo.getMemCode() == 3){		// 관리자
		memCode = vo.getMemCode();
		myPage = "/CodePeople/rehearsal/myPageAdmin.html";
	}
}else{
	
	
      out.write(" <script> location.href=\"/CodePeople/rehearsal/home.html\";</script> ");

	
}

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <title>");
      out.print(vo.getMemId() );
      out.write("님 환영합니다!</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap core JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/heroes/\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Etc -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/d3ee6ce800.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"/CodePeople/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/CodePeople/js/jquery.serializejson.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/CodePeople/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/CodePeople/css/intro.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/CodePeople/css/serch.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- External login lib -->\r\n");
      out.write("    <script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
      out.write("    <script src=\"https://apis.google.com/js/api.js\" async defer\r\n");
      out.write("    onreadystatechange=\"if (this.readyState === 'complete') this.onload()\"></script>\r\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js?onload=renderButton\" async defer></script>\r\n");
      out.write("    <script src=\"/CodePeople/js/googleLogin2.js\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script src=\"https://apis.google.com/js/api:client.js\"></script>\r\n");
      out.write("    <script src=\"/CodePeople/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- 헤더 -->\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("      <!-- 헤더 메인 메뉴 바 -->\r\n");
      out.write("      <div id=\"header-container\">\r\n");
      out.write("        <!-- 좌측 메뉴 -->\r\n");
      out.write("        <div id=\"header-left-menu\">\r\n");
      out.write("          <!-- 로고 -->\r\n");
      out.write("          <a href=\"#\" id=\"logo\"><i class=\"fas fa-copyright\" style=\"font-size: 32px;\"></i></a>\r\n");
      out.write("          <div class=\"divider\"></div>\r\n");
      out.write("          <!-- 검색창 -->\r\n");
      out.write("          <div id=\"search-box\">\r\n");
      out.write("            <div id=\"search-item\">\r\n");
      out.write("              <i class=\"fas fa-search item\" style=\"width:15.3px; height:19px;\"> </i>\r\n");
      out.write("              <input class=\"\" type=\"text\"\r\n");
      out.write("                style=\"height:19px; border:none;border-right:0px; border-top:0px; boder-left:0px; boder-bottom:0px;\"\r\n");
      out.write("                placeholder=\"통합검색\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 우측 메뉴 -->\r\n");
      out.write("        <div id=\"header-right-menu\">\r\n");
      out.write("          <!-- 메인 메뉴 링크 -->\r\n");
      out.write("          <div id=\"header-link-box\">\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/MainHR.do\">인재</a>\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/CompanyPagingList.do\">기업</a>\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/mainJsp/mainJO.jsp\">채용</a>\r\n");
      out.write("<!--             <a class=\"header-link\" href=\"/CodePeople/EachBoardPaging.do\">커뮤니티</a> -->\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/htmltest/boardFunctionTest.html\">커뮤니티</a>\r\n");
      out.write("            <a class=\"header-link myPage\" href=\"/CodePeople/GoMyPage.do\">마이페이지</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"divider\"></div>\r\n");
      out.write("          ");
if(vo.getMemIsApi() == 1){ 
      out.write("\r\n");
      out.write("          <a href=\"javascript:kakaoLogout()\"><button id=\"header-login-btn\" class=\"btn btn-primary btn-sm\">로그아웃</button></a>\r\n");
      out.write("          ");
} else { 
      out.write("\r\n");
      out.write("          <a href=\"/CodePeople/rehearsal/logout.jsp\" onclick=\"alert(`로그아웃되었습니다.`)\"><button id=\"header-login-btn\" class=\"btn btn-primary btn-sm\">로그아웃</button></a>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 인트로 메인화면 -->\r\n");
      out.write("    <main>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"home-first\">\r\n");
      out.write("        <div class=\"container col-10 col-xxl-8 px-4 py-5\">\r\n");
      out.write("          <div class=\"row align-items-center g-lg-5 py-5\">\r\n");
      out.write("            <div class=\"col-lg-7 text-center text-lg-start\">\r\n");
      out.write("              <!-- <h1 class=\"display-4 fw-bold lh-1 mb-3\"></h1> -->\r\n");
      out.write("              <p class=\"col-lg-10 fs-4\">\r\n");
      out.write("                <img src=\"/CodePeople/images/home.jpg\" alt=\"이미지 파일\" width=\"620px\" height=\"auto\">\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-10 mx-auto col-lg-5\">\r\n");
      out.write("              <form class=\"p-4 p-md-5 border rounded-3 bg-light\">\r\n");
      out.write("                <div class=\"profile\">\r\n");
      out.write("                  <h2 class=\"mb-4\">printf(\"hello world!\");</h2>\r\n");
      out.write("                  <a href=\"");
      out.print(myPage);
      out.write("\">\r\n");
      out.write("                    <img id=\"profile-img\" class=\"ui circular image\" src=\"");
      out.print(myProfileImg );
      out.write("\" alt=\"프로필이미지\">\r\n");
      out.write("                    <p class=\"profile-name\">");
      out.print(vo.getMemNm() );
      out.write("</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <!-- <p class=\"nowrap meta\">\r\n");
      out.write("                    마이페이지 넣어도 좋고, 나중에 기능 추가 가능\r\n");
      out.write("                      <a href=\"/@kimjihyunii\">\r\n");
      out.write("                      <span class=\"job-title\">TA</span>&nbsp;</a>\r\n");
      out.write("                    <a href=\"/companies/woowahan\">@카카오</a> \r\n");
      out.write("                  \r\n");
      out.write("                  </p> -->\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    \t코드피플에 오신 걸 환영합니다!<br>\r\n");
      out.write("                    \t다양한 소식을 받아보세요.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- popup for ID -->\r\n");
      out.write("      <div class=\"modal fade\" id=\"id_form\" tabindex=\"-1\" aria-labelledby=\"searchIdLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("              <p class=\"modal-title\" id=\"searchIdLabel\">아이디 찾기</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"request\">\r\n");
      out.write("                <div class=\"basic header\">\r\n");
      out.write("                  <p>가입하신 이름과 이메일 주소를 입력해 주세요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                  <label for=\"name\" class=\"form-label\">이름</label>\r\n");
      out.write("                  <input type=\"text\" id=\"name\" class=\"form-control\" value=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                  <label for=\"email\" class=\"form-label\">이메일 주소</label>\r\n");
      out.write("                  <input type=\"email\" id=\"email\" class=\"form-control\" value=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary\">찾기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- popup for Password -->\r\n");
      out.write("      <div class=\"modal fade\" id=\"pass_form\" tabindex=\"-1\" aria-labelledby=\"searchPassLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("              <p class=\"modal-title\" id=\"searchPassLabel\">비밀번호 찾기</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"request\">\r\n");
      out.write("                <div class=\"basic header\">\r\n");
      out.write("                  <p>가입하신 아이디와 이메일 주소를 입력해 주세요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                  <label for=\"id\" class=\"form-label\">비밀번호</label>\r\n");
      out.write("                  <input type=\"text\" id=\"id\" class=\"form-control\" value=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                  <label for=\"email\" class=\"form-label\">이메일 주소</label>\r\n");
      out.write("                  <input type=\"email\" id=\"email\" class=\"form-control\" value=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary\">찾기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"home-second\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mt-5 text-center\">\r\n");
      out.write("  \r\n");
      out.write("          <h3 class=\"display-6 fw-bold\">코드피플에 있는 사람들과 연결해보세요.</h3>\r\n");
      out.write("          <div class=\"col-lg-6 mx-auto\">\r\n");
      out.write("            <p class=\"lead mb-4\">다양한 분야의 사람들과 기업들이 교류하고 있는 코드피플 커뮤니티에 합류하세요!</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"d-grid gap-2 justify-content-sm-center\">\r\n");
      out.write("              <div class=\"user-list\">\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img class=\"ui circular image\" src=\"/CodePeople/images/blue.jpg\" alt=\"김진혁\">\r\n");
      out.write("                    <p class=\"name\">김진혁</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <p class=\"nowrap meta\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <span class=\"job-title\">TA</span>&nbsp;</a>\r\n");
      out.write("                    <a href=\"/companies/woowahan\">@카카오</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    Salanghaeyo kakao. salanghaeyo gimbeomsu hyeongnim.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img class=\"ui circular image\" src=\"/CodePeople/images/pink.jpg\" alt=\"마창수\">\r\n");
      out.write("                    <p class=\"name\">마창수</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <p class=\"nowrap meta\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <span class=\"job-title\">DA</span>&nbsp;</a>\r\n");
      out.write("                    <a href=\"/companies/naver\">@고고IT회사</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    Tôi không nói được tiếng Hàn. Xin chào. Rất vui được gặp bạn. Tôi học hôm nay. tôi yêu bạn cái đuôi.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img class=\"ui circular image\" src=\"/CodePeople/images/red.jpg\" alt=\"이광효\">\r\n");
      out.write("                    <p class=\"name\">이광효</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <p class=\"nowrap meta\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <span class=\"job-title\">PL (팀장)</span>&nbsp;</a>\r\n");
      out.write("                      <a href=\"/companies/yanolja\">@네이버</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    I am a leader. i am a leader. i am a leader. i am a DBA\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img class=\"ui circular image\" src=\"/CodePeople/images/yellow.jpg\" alt=\"임나리\">\r\n");
      out.write("                    <p class=\"name\">임나리</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <p class=\"nowrap meta\">\r\n");
      out.write("                    <a href=\"#\"><span class=\"job-title\">UA</span>&nbsp;</a>\r\n");
      out.write("                    <a href=\"/companies/sendbird\">@애플</a></p>\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    Trust me, Apple is the best company in the world. SamSung? who cares (lol)\r\n");
      out.write("                  </p>\r\n");
      out.write("              \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <img class=\"ui circular image\" src=\"/CodePeople/images/green.jpg\" alt=\"양기욱\">\r\n");
      out.write("                    <p class=\"name\">양기욱</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <p class=\"nowrap meta\"><a href=\"/@iamzenon\">\r\n");
      out.write("                    <span class=\"job-title\">AA</span>&nbsp;</a>\r\n");
      out.write("                    <a href=\"/companies/cupist\">@구글</a></p>\r\n");
      out.write("                  <p class=\"break testimonial\">\r\n");
      out.write("                    Google is the best. simply say, there is no company can follow Google's convenience. Apple? poo~ (laughing)\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"company-list\">\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                <a href=\"https://toss.im/career\">\r\n");
      out.write("                  <img class=\"ui circular image\" src=\"https://image.rocketpunch.com/company/233/vivarepublica_logo_1548980012.png?s=100x100&amp;t=inside\" alt=\"비바리퍼블리카(토스)\">\r\n");
      out.write("                  <p class=\"name\">비바리퍼블리카(토스)</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p class=\"break testimonial\">\r\n");
      out.write("                  금융이 쉬워진다 Toss토스팀은 금융의 문제를 해결하려 합니다.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <a href=\"https://team.daangn.com/jobs/\">\r\n");
      out.write("                  <img class=\"ui circular image\" src=\"/CodePeople/images/Daangeun_Logo.jpg\" alt=\"당근마켓\">\r\n");
      out.write("                  <p class=\"name\">당근마켓</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p class=\"break testimonial\">\r\n");
      out.write("                  \t이웃이 알려주는 진짜 우리 동네 정보, 내 근처에 숨어있는 좋은 가게를 발견하고, 이웃과 함께 소소한 일상을 나눌 수 있는 따뜻하고 풍요로운 동네 생활을 꿈꿔요.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <a href=\"https://recruit.navercorp.com/naver/recruitMain\">\r\n");
      out.write("                  <img class=\"ui circular image\" src=\"https://seoulsochic.com/skin/m_modern/images/button/naver-icon.png\" alt=\"네이버\">\r\n");
      out.write("                  <p class=\"name\">네이버</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p class=\"break testimonial\">\r\n");
      out.write("                국내  No. 1 검색 포털 네이버, 국내 최초 어린이 전용 포털 쥬니어네이버,\r\n");
      out.write("                 국내 최초 온라인 기부 포털 해피빈을 운영하고 있는 국내 최고의 인터넷\r\n");
      out.write("                  전문 기업입니다.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <a href=\"https://www.woowahan.com/\">\r\n");
      out.write("                  <img class=\"ui circular image\" src=\"https://officen.azureedge.net/upload/editor/53600b76-ac7b-4a56-9b2f-161655dbcb5f.jpg\" alt=\"우아한형제들\">\r\n");
      out.write("                  <p class=\"name\">우아한형제들</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p class=\"break testimonial\">\r\n");
      out.write("                  세상의 발전에 도움이 되고\r\n");
      out.write("                  세상을 조금 더 ‘우아~’하게 만들 수 있는 기업이 되기 위해 노력하고 있습니다.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <a href=\"https://careers.kakao.com/index\">\r\n");
      out.write("                  <img class=\"ui circular image\" src=\"https://t1.kakaocdn.net/kakaocorp/corp_thumbnail/Kakao.png\" alt=\"카카오\">\r\n");
      out.write("                  <p class=\"name\">카카오</p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <p class=\"break testimonial\">\r\n");
      out.write("                  카카오는 시공간의 한계를 뛰어넘어 사람과 사람, 사람과 세상을 이어줍니다.\r\n");
      out.write("                  연결의 혁신으로 세상은 더욱 가깝고 새로워진다고 카카오는 믿습니다.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("  \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"home-third\">\r\n");
      out.write("        <div class=\"container col-xxl-8 px-4 py-5\">\r\n");
      out.write("          <div class=\"row align-items-center g-5 py-5\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <h2 class=\"fw-bold lh-1 mb-3 bt-6\">좋은 회사, 좋은 인력이 소통하는 공간을 만드는 코드피플이 되겠습니다.</h2>\r\n");
      out.write("              <p class=\"lead\">나와 연결된 사람과 내가 연결한 기업의 소식을 받아보고, 관심 태그 기반으로 다양한 소식도 받아보세요. 흥미로운 사람이 있다면 관심 등록을 할수도 있습니다.</p>\r\n");
      out.write("              <div class=\"d-grid gap-2 d-md-flex justify-content-md-start\">\r\n");
      out.write("                <!-- <button type=\"button\" class=\"btn btn-primary btn-lg px-4 me-md-2\">Primary</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary btn-lg px-4\">Default</button> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-10 col-sm-8 col-lg-6\">\r\n");
      out.write("              <img src=\"../images/timeline2.png\" alt=\"Bootstrap Themes\" width=\"610\"\r\n");
      out.write("                height=\"597\" loading=\"lazy\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"home-fourth py-5\">\r\n");
      out.write("        <div class=\"container my-5\">\r\n");
      out.write("          <div class=\"row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg\">\r\n");
      out.write("            <div class=\"col-lg-7 p-3 p-lg-5 pt-lg-3\">\r\n");
      out.write("              <h1 class=\"display-4 fw-bold lh-1\">코드피플은 기업과 개인간의 소통의 장소입니다.</h1>\r\n");
      out.write("              <p class=\"lead\">내가 관심 있는 기업들을 팔로우하고 그 기업들의 뉴스, 채용 정보 등, 다양한 정보를 발견해 보세요.</p>\r\n");
      out.write("              <div class=\"d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3\">\r\n");
      out.write("                <!-- <button type=\"button\" class=\"btn btn-primary btn-lg px-4 me-md-2 fw-bold\">Primary</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary btn-lg px-4\">Default</button> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg\">\r\n");
      out.write("              <img class=\"rounded-lg-3\" src=\"../images/jobs.png\" alt=\"\" width=\"720\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <div class=\"home-fifth\">\r\n");
      out.write("        <div class=\"bg-dark text-secondary text-center\">\r\n");
      out.write("          <div class=\"py-2\">\r\n");
      out.write("            <!-- <h1 class=\"display-5 fw-bold text-white  \">footer 양식 넣어주세요.</h1> -->\r\n");
      out.write("            <div class=\"col-lg-6 mx-auto\">\r\n");
      out.write("              <p class=\"mb-4\">\r\n");
      out.write("                상호명: 얼씨구 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                대표자 : 얼씨구 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                사업자등록번호: 000-11-00000 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                직업정보제공사업 신고번호: J1206020160003 <br>\r\n");
      out.write("                주소 : 서울특별시 서초구 강남대로51길 10 15층 1519호 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 전화번호 : 02-877-7624 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 이메일 : startup@rocketpunch.com\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"d-grid gap-2 d-sm-flex justify-content-sm-center\">\r\n");
      out.write("                <!-- <button type=\"button\" class=\"btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold\">Custom button</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-light btn-lg px-4\">Secondary</button> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    </main>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"/CodePeople/js/kakaoLogin.js\"></script> \r\n");
      out.write("  <script src=\"/CodePeople/js/naverLogin.js\"></script> \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
