/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-25 03:37:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainJsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.hr.vo.HRMyInfoVO;
import kr.or.ddit.hr.vo.HRCrrVO;
import kr.or.ddit.cv.vo.CVVO;
import kr.or.ddit.certification.vo.CertificationVO;
import kr.or.ddit.progLang.vo.ProgLangVO;
import kr.or.ddit.hr.vo.HRInfoVO;
import kr.or.ddit.edu.vo.EduVO;
import java.util.List;

public final class hrMyInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.progLang.vo.ProgLangVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRInfoVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRCrrVO");
    _jspx_imports_classes.add("kr.or.ddit.edu.vo.EduVO");
    _jspx_imports_classes.add("kr.or.ddit.cv.vo.CVVO");
    _jspx_imports_classes.add("kr.or.ddit.certification.vo.CertificationVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRMyInfoVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int memNo = (int)(request.getAttribute("memNo"));
int hrNo = (int)(request.getAttribute("hrNo"));

int certListSize = (int)(request.getAttribute("certListSize"));
int plListSize = (int)(request.getAttribute("plListSize"));
int crrListSize = (int)(request.getAttribute("crrListSize"));
int eduListSize = (int)(request.getAttribute("eduListSize"));

int infoFlag = (int)request.getAttribute("infoFlag");




      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/d3ee6ce800.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- 헤더 -->\r\n");
      out.write("  <div id=\"header\">\r\n");
      out.write("    <!-- 헤더 메인 메뉴 바 -->\r\n");
      out.write("    <div id=\"header-container\">\r\n");
      out.write("      <!-- 좌측 메뉴 -->\r\n");
      out.write("      <div id=\"header-left-menu\">\r\n");
      out.write("        <!-- 로고 -->\r\n");
      out.write("        <a href=\"\" id=\"logo\"><i class=\"fas fa-copyright\" style=\"font-size: 32px;\"></i></a>\r\n");
      out.write("        <div class=\"divider\"></div>\r\n");
      out.write("        <!-- 통합 검색창 -->\r\n");
      out.write("        <div id=\"search-box\">\r\n");
      out.write("          <div id=\"search-item\">\r\n");
      out.write("            <i class=\"fas fa-search item\" style=\"width: 15.3px; height: 19px;\">\r\n");
      out.write("            </i> <input class=\"\" type=\"text\"\r\n");
      out.write("              style=\"height: 19px; border: none; border-right: 0px; border-top: 0px; boder-left: 0px; boder-bottom: 0px;\"\r\n");
      out.write("              placeholder=\"통합검색\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 우측 메뉴 -->\r\n");
      out.write("      <div id=\"header-right-menu\">\r\n");
      out.write("        <!-- 메인 메뉴 링크 -->\r\n");
      out.write("        <div id=\"header-link-box\">\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/MainHR.do\">인재</a>\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/CompanyPagingList.do\">기업</a>\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/mainJsp/mainJO.jsp\">채용</a>\r\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/EachBoardPaging.do\">커뮤니티</a>\r\n");
      out.write("            <a class=\"header-link myPage\" href=\"/CodePeople/GoMyPage.do\">마이페이지</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"divider\"></div>\r\n");
      out.write("        <!-- 로그인버튼 -->\r\n");
      out.write("        <a href=\"/CodePeople/rehearsal/home.html\"><button id=\"header-login-btn\"\r\n");
      out.write("            class=\"btn btn-primary btn-sm\">로그인</button></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- 바디 -->\r\n");
      out.write("  <div id=\"body\">\r\n");
      out.write("    <div id=\"body-container\">\r\n");
      out.write("      <!-- 마이페이지 좌측 메뉴바 -->\r\n");
      out.write("      <div class=\"nav-left-bar nav-my\">\r\n");
      out.write("        <div class=\"nav-sticky\">\r\n");
      out.write("          <ul class=\"list-group\">\r\n");
      out.write("            <li class=\"list-group-item \"><a class=\"nav-link\" href=\"/CodePeople/rehearsal/HRInfoModify.html\">수정하기</a></li>\r\n");
      out.write("          \r\n");
      out.write("            <li class=\"list-group-item\"><a class=\"nav-link\" href=\"#edu\">학력</a></li>\r\n");
      out.write("            <li class=\"list-group-item\"><a class=\"nav-link\" href=\"#crr\">경력</a></li>\r\n");
      out.write("            <li class=\"list-group-item\"><a class=\"nav-link\" href=\"#pl\">활동분야</a></li>\r\n");
      out.write("            <li class=\"list-group-item\"><a class=\"nav-link\" href=\"#cert\">자격증</a></li>\r\n");
      out.write("          \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 바디 콘텐츠 -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <!-- 마이페이지 -->\r\n");
      out.write("\t\t<!--기본정보   -->\r\n");
      out.write("\t\t<div id=\"cv\" class=\"content-box search-result jo my-main-cv\">\r\n");
      out.write("                    <div class=\"my-box-item\">\r\n");
      out.write("                        <div class=\"my-box-header\">\r\n");
      out.write("                            <h1 class=\"h1\">인재정보</h1>\r\n");
      out.write(" ");

 if (infoFlag == 0){

      out.write("                             \r\n");
      out.write("                            <div class=\"my-btn-box\">                           \r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-primary\">등록</button>\r\n");
      out.write("                            </div>\r\n");
      out.write(" ");
 
 
  }
 
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write(" ");

 if (infoFlag == 0){

      out.write("\r\n");
      out.write("\t <p> 입력하신 정보가 없습니다.</p>\r\n");
 
 }else{
	HRMyInfoVO myInfoVO = (HRMyInfoVO)request.getAttribute("myInfoVO");
	String hrOpen = "";
	if(myInfoVO.getHrOpen()==0){
		hrOpen="비공개";
	}else{
		hrOpen="공개";
	}

      out.write("\t \r\n");
      out.write(" <!-- 검색결과 카드 -->\r\n");
      out.write("                    <div class=\"card card-cv\">\r\n");
      out.write("                        <!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\r\n");
      out.write("                        <div class=\"card-left\">\r\n");
      out.write("                            <img src=\"\" alt=\"Card image\" style=\"width:64px; height: 64px;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 카드의 정보 -->\r\n");
      out.write("                        <div class=\"card-body card-right\">\r\n");
      out.write("                            <div class=\"card-top-box\">\r\n");
      out.write("                                <h4 class=\"card-title cv-title\">");
      out.print(myInfoVO.getHrCmt() );
      out.write("</h4>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 카드의 회사 소개, 직군 -->  \r\n");
      out.write("                                            \r\n");
      out.write("                            <div >\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">이름 </label><span class=\"memNm\" name=\"memNo\" value=\"");
      out.print(myInfoVO.getMemNo());
      out.write('"');
      out.write('>');
      out.print(myInfoVO.getMemNm() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div >\r\n");
      out.write("                           <label style=\"display: inline-block; width: 80px; font-weight: bold;\">직군  </label><span class=\"jgCodeNm\" name=\"jgCodeNo\" value=\"");
      out.print(myInfoVO.getJgCodeNo());
      out.write('"');
      out.write('>');
      out.print(myInfoVO.getJgCodeNm() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">직무  </label><span class=\"jtCodeNm\" name=\"jtCodeNo\" value=\"");
      out.print(myInfoVO.getJtCodeNo());
      out.write('"');
      out.write('>');
      out.print(myInfoVO.getJtCodeNm() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">재직회사  </label><span class=\"hrCurrCom\">");
      out.print(myInfoVO.getHrCurrCom() );
      out.write("</span>\r\n");
      out.write("                           \t</div>\r\n");
      out.write("                           \t<div>\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">희망연봉  </label><span class=\"hrSal\">");
      out.print(myInfoVO.getHrSal() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">한마디  </label><span class=\"hrCmt\">");
      out.print(myInfoVO.getHrCmt() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            <label style=\"display: inline-block; width: 80px; font-weight: bold;\">자기소개 </label><span class=\"hrIntro\">");
      out.print(myInfoVO.getHrIntro() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         \r\n");
      out.write("                          \t<div>\r\n");
      out.write("                           <label style=\"display: inline-block; width: 80px; font-weight: bold;\">공개여부  </label><span class=\"hrOpen\">");
      out.print(hrOpen );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("      \r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t \r\n");
	 
 }
 
      out.write(" \r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 학력-->\r\n");
      out.write("        <div id=\"edu\" class=\"content-box search-result board board-main board-best\">\r\n");
      out.write("          <div class=\"board-header\">\r\n");
      out.write("            <div class=\"board-name\">\r\n");
      out.write("              <h1 class=\"h1\">학력</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"board-body\">\r\n");
      out.write("            <div class=\"divider\"></div>\r\n");
      out.write("            <!-- 아코디언 : 게시판 게시글들 시작 -->\r\n");
      out.write("            <div id=\"accordion\">\r\n");
 
		if(eduListSize==0){

      out.write("\t\t\r\n");
      out.write("\t\t<p style=\"text-align: center;\">학력정보가 없습니다.</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
		
		}else{
			List<EduVO> eduList = (List<EduVO>)request.getAttribute("eduList");
			for(int i = 0; i< eduList.size(); i++){
				EduVO edu = eduList.get(i);
				if(!edu.getEduCodeNm().equals("학력무관") ){
				 String eduSchNm = edu.getEduSchNm();
				 String eduMajor = edu.getEduMajor();
			
				 if(eduSchNm=="0"){
					 eduSchNm = "기재사항 없음";
				 }
				 if(eduMajor=="0"){
					 eduMajor = "기재사항 없음";
				 }
					

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<!-- 게시글의 한단위  -->\r\n");
      out.write("              <!-- card-hear 안 a태그와 게시글의 아이디를 맞춰주세요 -->\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("\t\t\t\t  <a class=\"btn title-btn\" data-bs-toggle=\"collapse\" href=\"#edu");
      out.print(i);
      out.write("\">\r\n");
      out.write("\t\t\t\t학력구분&nbsp;&nbsp;:&nbsp;&nbsp;<span class=\"board-title eduCodeNm\">");
      out.print(edu.getEduCodeNm());
      out.write("</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 게시글을 담고있는 곳 a 태그가 가르키는 곳 -->\r\n");
      out.write("                <div id=\"edu");
      out.print(i);
      out.write("\" class=\"collapse \" data-bs-parent=\"#accordion\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    <span class=\"board-detail-content\">\r\n");
      out.write("                      <label for=\"\">구분&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduCodeNm\" >");
      out.print(edu.getEduCodeNm());
      out.write("</span><br>\r\n");
      out.write("                      <label for=\"\">학교&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduSchNm\" >");
      out.print(eduSchNm);
      out.write("</span><br>\r\n");
      out.write("                      <label for=\"\">전공&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduMajor\" >");
      out.print(eduMajor);
      out.write("</span><br>\r\n");
      out.write("       \r\n");
      out.write("  \r\n");
      out.write("         ");

         					if(edu.getEduCodeNm().equals("고등학교졸업") ){
         
      out.write("\r\n");
      out.write("         \t\t\t\t   <label for=\"\">평점&nbsp;</label>:&nbsp;&nbsp;해당없음<br>\r\n");
      out.write("                   \t\r\n");
      out.write("         \t\t\t\t\t\r\n");
      out.write("         ");
 					
         					}else{
         
      out.write("\r\n");
      out.write("                      <label for=\"\">평점&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduGraAvg\" >");
      out.print(edu.getEduGraAvg());
      out.write("</span> &nbsp;/&nbsp;<span class=\"board-title eduGraTot\" >");
      out.print(edu.getEduGraTot() );
      out.write("</span><br>\r\n");
      out.write("                    </span>\r\n");
      out.write("          ");

         					 } 
          
      out.write("     \r\n");
      out.write("                   \r\n");
      out.write("                  </div>          \r\n");
      out.write("                </div>\r\n");
      out.write("                     <div class=\"my-btn-box my-btn-box-cv\">\r\n");
      out.write("                           <a href=\"/CodePeople/rehearsal/EduDelete.jsp?hrNo=");
      out.print(hrNo);
      out.write("&eduNo=");
      out.print(edu.getEduNo());
      out.write("&eduCodeNo=");
      out.print(edu.getEduCodeNo());
      out.write("\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-primary\">삭제</button></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("              </div>\r\n");
 				
				}
			}
		}

      out.write("\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 경력 -->\r\n");
      out.write("        <div id=\"crr\" class=\"content-box search-result board board-main board-best\">\r\n");
      out.write("          <div class=\"board-header\">\r\n");
      out.write("            <div class=\"board-name\">\r\n");
      out.write("              <h1 class=\"h1\">경력</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"board-body\">\r\n");
      out.write("            <div class=\"divider\"></div>\r\n");
      out.write("            <!-- 아코디언 : 게시판 게시글들 시작 -->\r\n");
      out.write("            <div id=\"accordion\">\r\n");
      out.write("              <!-- 게시글의 한단위  -->\r\n");
      out.write("              <!-- card-hear 안 a태그와 게시글의 아이디를 맞춰주세요 -->\r\n");
      out.write("              \r\n");

	if(crrListSize==0){

      out.write("\r\n");
      out.write("\t<p style=\"text-align: center;\">경력정보가 없습니다.</p>\r\n");
 	
	}else{
		List<HRCrrVO> crrList = (List<HRCrrVO>)request.getAttribute("crrList"); 
		for(int i = 0; i < crrList.size(); i++){
			HRCrrVO crr = crrList.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t    <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                  <a class=\"btn title-btn\" data-bs-toggle=\"collapse\" href=\"#or\">\r\n");
      out.write("                    <span class=\"board-title crrCompNm\"  >");
      out.print(crr.getCrrCompNm() );
      out.write("</span>&nbsp;&nbsp;&nbsp;<span class=\"board-title jtCodeNo\" >");
      out.print(crr.getJtCodeNm() );
      out.write("</span>&nbsp;&nbsp;(<span class=\"board-title crrYears\" >6</span>년차)\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 게시글을 담고있는 곳 a 태그가 가르키는 곳 -->\r\n");
      out.write("                <div id=\"or\" class=\"collapse \" data-bs-parent=\"#accordion\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                   \r\n");
      out.write("                    <span class=\"board-detail-content\">\r\n");
      out.write("                      <label for=\"\">회사&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title crrCompNm\" >");
      out.print(crr.getCrrCompNm() );
      out.write("</span><br>\r\n");
      out.write("                      <label for=\"\">직급&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title crrRank\" >");
      out.print(crr.getCrrRank() );
      out.write("</span><br>\r\n");
      out.write("                      <label for=\"\">연차&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title crrYears\" >");
      out.print(crr.getCrrYears() );
      out.write("</span>년차<br>\r\n");
      out.write("                      <label for=\"\">직군&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title jgCodeNo\" >");
      out.print(crr.getJgCodeNm() );
      out.write("</span><br>\r\n");
      out.write("                      <label for=\"\">직무&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title jtCodeNo\" >");
      out.print(crr.getJtCodeNm() );
      out.write("</span>\r\n");
      out.write("                      \r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                \r\n");
      out.write("            \r\n");
      out.write("                </div>\r\n");
      out.write("                     <div class=\"my-btn-box my-btn-box-cv\">\r\n");
      out.write("                            \r\n");
      out.write("                                <a href=\"/CodePeople/rehearsal/CrrDelete.jsp?hrNo=");
      out.print(hrNo);
      out.write("&crrNo=");
      out.print(crr.getCrrNo() );
      out.write("\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-primary\">삭제</button></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("              </div>\t\t\t\t\r\n");
      out.write("\t\t\t");

		}
	}

      out.write("              \r\n");
      out.write(" \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 활동분야  -->\r\n");
      out.write("        <div id=\"pl\" class=\"content-box search-result board board-main board-best\">\r\n");
      out.write("          <div class=\"board-header\">\r\n");
      out.write("            <div class=\"board-name\">\r\n");
      out.write("              <h1 class=\"h1\">활동분야</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("     \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"divider\"></div>\r\n");

if (plListSize==0){

      out.write("\r\n");
      out.write("<p style=\"text-align: center;\">활동분야 정보가 없습니다.</p>\r\n");
 	
}else{
	List<ProgLangVO> plList = (List<ProgLangVO>)request.getAttribute("plList"); 	
	for(int i = 0 ; i < plList.size() ; i ++){
		ProgLangVO pl = plList.get(i);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"board-card\">\r\n");
      out.write("            <div class=\"board-detail\">\r\n");
      out.write("              <a href=\"#\" class=\"card-link\"><span class=\"board-title company-name plCodeNm\" >");
      out.print(pl.getPlCodeNm() );
      out.write("</span></a>&nbsp;&nbsp;\r\n");
      out.write("            </div>\r\n");
      out.write("                 <div class=\"my-btn-box my-btn-box-cv\">                      \r\n");
      out.write("                                <a href=\"/CodePeople/rehearsal/PlDelete.jsp?hrNo=");
      out.print(hrNo);
      out.write("&plCodeNo=");
      out.print(pl.getPlCodeNo() );
      out.write("\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-outline-primary\">삭제</button></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
 		
	}
}

      out.write("                \r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 자격증  -->\r\n");
      out.write("        <div id=\"cert\" class=\"content-box search-result board board-main board-best\">\r\n");
      out.write("          <div class=\"board-header\">\r\n");
      out.write("            <div class=\"board-name\">\r\n");
      out.write("              <h1 class=\"h1\">자격증</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"divider\"></div>\r\n");
 
	if(certListSize==0){

      out.write("\r\n");
      out.write("<p style=\"text-align: center;\">자격증 정보가 없습니다.</p>\r\n");
		
	}else{
		List<CertificationVO> certList = (List<CertificationVO>)request.getAttribute("certList");
		for(int i = 0 ; i < certList.size(); i ++){
		CertificationVO cert = certList.get(i);

      out.write("\r\n");
      out.write("  \t\t<div class=\"board-card\">\r\n");
      out.write("            <div class=\"board-detail\">\r\n");
      out.write("              <a href=\"#\" class=\"card-link\"><span class=\"board-title company-name certCodeNm\" >");
      out.print(cert.getCertCodeNm() );
      out.write("</span></a>&nbsp;&nbsp;          \r\n");
      out.write("            </div>\r\n");
      out.write("                 <div class=\"my-btn-box my-btn-box-cv\">\r\n");
      out.write("                                <a href=\"/CodePeople/rehearsal/CertDelete.jsp?hrNo=");
      out.print(hrNo);
      out.write("&certCodeNo=");
      out.print(cert.getCertCodeNo() );
      out.write("\"><button type=\"button\" class=\"btn btn-outline-primary\">삭제</button></a>\r\n");
      out.write("                                \r\n");
      out.write("                                <script type=\"text/javascript\">\r\n");
      out.write("                                 function certDelete(){\r\n");
      out.write("                              \t\t \r\n");
      out.write("                                 }\r\n");
      out.write("                              \r\n");
      out.write("                                </script>\r\n");
      out.write("                 </div>\r\n");
      out.write("          </div>\r\n");
						
		}
	}

      out.write("          \r\n");
      out.write("  \r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("      </div>\r\n");
      out.write("  <!--  풋터-->\r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("    <div id=\"footer-container\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
