/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-10-26 00:16:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainJsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.company.service.CompanyServiceImpl;
import kr.or.ddit.company.service.ICompanyService;
import kr.or.ddit.company.vo.CompanyVO;
import kr.or.ddit.cmm.util.SessionCheck;
import kr.or.ddit.member.vo.MemberVO;

public final class companyInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.cmm.util.SessionCheck");
    _jspx_imports_classes.add("kr.or.ddit.member.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.company.service.ICompanyService");
    _jspx_imports_classes.add("kr.or.ddit.company.vo.CompanyVO");
    _jspx_imports_classes.add("kr.or.ddit.company.service.CompanyServiceImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int memCode = 0;
	int memNo = 0;
	int hrNo = 0;
	int cnt = 0;
	int comNo = 0;
	MemberVO loginMember = null;
	CompanyVO cv = null;
	if(SessionCheck.isLoginMember(session)){
		
		loginMember = (MemberVO)session.getAttribute("memVO");
		
		// 로그인 상태인 경우
		memCode = SessionCheck.getMemCode(session, request);
		memNo = SessionCheck.getMemNo(session, request);
		if(memCode == 1){
			// 개인회원인 경우
			hrNo = SessionCheck.getHrNo(session, request);
			System.out.println(hrNo);
			
			
      out.write(" <script>\talert(\"기업 회원만 이용 가능합니다.\")\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/CodePeople/rehearsal/company.jsp\" </script> ");

		}else if(memCode == 2){

			// 기업회원인 경우
			cnt = SessionCheck.hasComNo(session, request);
			System.out.println(cnt);
			if(cnt > 0){
				// 기업을 등록한 기업회원인 경우
				comNo = SessionCheck.getComNo(session, request);
				System.out.println(comNo);
				ICompanyService companyService = CompanyServiceImpl.getInstance();
				cv = companyService.getCompany(comNo);
				System.out.println(cv);
				
			}
		}
	}else{
		
		// 비회원인 경우
		//로그인 정보없이 접근했을 경우 home.html으로 돌려보냄
				
      out.write(" <script> alert(\"해당 권한이 없습니다.\");\tlocation.href=\"/CodePeople/rehearsal/home.html\"\t</script>\t");

		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src='https://www.google.com/recaptcha/api.js'></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"/CodePeople/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"/CodePeople/js/jquery.serializejson.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/CodePeople/js/company.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/CodePeople/css/join.css\">\r\n");
      out.write("<style>\r\n");
      out.write("  .mb-3{\r\n");
      out.write("  \twidth: 500px;\r\n");
      out.write("  \tmargin:0 auto;\r\n");
      out.write("  }\r\n");
      out.write("  body{\r\n");
      out.write("  \tbackground-image:  linear-gradient(\r\n");
      out.write("        to right bottom,\r\n");
      out.write("        rgba(232, 232, 232, 0.6),\r\n");
      out.write("        rgba(191, 191, 191, 0.3)),url(\"/CodePeople/images/companyInsert.jpg\");\r\n");
      out.write("  \theight: 100%;\r\n");
      out.write("  \topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("  }\r\n");
      out.write("  div{\r\n");
      out.write("  \t\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 

//기업 정보가 있는 회원
if(cnt > 0){


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container mt-3 formsizing company-register\">\r\n");
      out.write("\t\t<img src=\"/CodePeople/images/codeppl_remove.png\" alt=\"코드피플_회원가입이미지\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: auto; margin-right: auto; display: block;\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"/action_page.php\" id=\"comInsert\">\r\n");
      out.write("\t\t\t<div class=\"mb-3 mt-3\">\r\n");
      out.write("\t\t\t\t<label>한글 기업명</label> <br> <label class=\"la2\" for=\"email\">*&nbsp;주식회사,\r\n");
      out.write("\t\t\t\t\t(주) 등의 표기 없이 입력해주세요</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"name\" placeholder=\"예) 기업명 \" name=\"comNm\" value=\"");
      out.print( cv.getComNm() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>사원 수</label> <input type=\"number\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"emp\" placeholder=\"사원 수를 입력해주세요.('명'은 생략)\" name=\"comCnt\" value=\"");
      out.print( cv.getComCnt() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>홈페이지 주소</label> <input type=\"url\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"company\" placeholder=\"홈페이지 주소를 입력해주세요\" name=\"comHpg\" value=\"");
      out.print( cv.getComHpg() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>평균 연봉</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"salary\" placeholder=\"평균 연봉을 입력해주세요.('만 원'은 생략)\" name=\"comSal\" value=\"");
      out.print( cv.getComSal() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>설립일</label> <input type=\"date\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"company-date\" placeholder=\"설립일을 입력해주세요.\" name=\"comDate\" value=\"");
      out.print( cv.getComDate() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>회사 한줄 소개</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"introdce\" placeholder=\"회사 한줄 소개를 입력해주세요.\" name=\"comIntro\" value=\"");
      out.print( cv.getComIntro() );
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>회사 상세 소개</label> <br>\r\n");
      out.write("\t\t\t\t<textarea style=\"height: 200px; width: 100%;\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"introdce\" placeholder=\"회사 한줄 소개를 입력해주세요.\"\r\n");
      out.write("\t\t\t\t\tname=\"comDetail\">");
      out.print( cv.getComDetail() );
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"dropdown mb-3\">\r\n");
      out.write("\t\t\t\t<label>직군</label> <br> <label class=\"la2\">*&nbsp;더 많은\r\n");
      out.write("\t\t\t\t\t사람이 회원님의 기업을 쉽게 찾을 수 있도록 산업 분야를 추가해주세요.</label> <br>\r\n");
      out.write("\t\t\t\t<div id=\"search-item\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"jgval\" type=\"text\"\tplaceholder=\"직군 검색\" disabled>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\"\tid=\"jgCodeNo\" type=\"text\" name=\"jgCodeNo\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"jobgroupbtn\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\">직군\r\n");
      out.write("\t\t\t\t\t선택</button>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 1</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 2</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 3</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3 zip\">\r\n");
      out.write("\t\t\t\t<label>우편번호</label>\r\n");
      out.write("\t\t\t\t<div class=\"zipInput\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control zip\" id=\"postCode\" disabled>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" onclick=\"proc();\" value=\"우편번호 검색\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>주소1</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"roadAddress\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>주소2</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"detailAddress\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"cityCodeNo\"\r\n");
      out.write("\t\t\t\t\tname=\"cityCodeNo\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"provCodeNo\"\r\n");
      out.write("\t\t\t\t\tname=\"provCodeNo\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>사업자 등록 번호</label><br> <label class=\"la2\">*&nbsp;사업자\r\n");
      out.write("\t\t\t\t\t등록번호는 기업관리자만 볼 수 있습니다.</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"companynum\" placeholder=\"사업자 등록번호를 입력해주세요.\" name=\"companynum\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>기업 공식 이메일</label> <br> <label class=\"la2\">*&nbsp;기업\r\n");
      out.write("\t\t\t\t\t공식 도메인의 이메일(@회사명.com)을 입력해주세요.</label> <label class=\"la2\">*&nbsp;해당\r\n");
      out.write("\t\t\t\t\t이메일로 인증 메일을 보내드립니다. 인증 시 기업 회원으로 등록됩니다.</label> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"companyEmail\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"기업 공식 이메일을 입력해주세요.\" name=\"companyEmail\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>문의 담당자</label><br> <label class=\"la2\">*&nbsp;기업\r\n");
      out.write("\t\t\t\t\t페이지를 처음 등록한 분이 문의 담당자로 지정됩니다.</label> <label class=\"la2\">*&nbsp;변경하려면\r\n");
      out.write("\t\t\t\t\t기업 등록 후 '기업 프로필>기업 정보'에서 변경 및 삭제해주세요.</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"officer\" placeholder=\"ex)Elon Reeve Musk\"\r\n");
      out.write("\t\t\t\t\tname=\"officer\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"memNo\" name=\"memNo\" value=\"");
      out.print( memNo );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"comNo\" name=\"comNo\" value=\"");
      out.print( comNo );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn-center-box\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"upd-btn\">수정</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"del-btn\">삭제</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
 //기업정보가 없는 회원
	} else { 

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container mt-3 formsizing company-register\">\r\n");
      out.write("\t\t<img src=\"/CodePeople/images/codeppl_remove.png\" alt=\"코드피플_회원가입이미지\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: auto; margin-right: auto; display: block;\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"/action_page.php\" id=\"comInsert\">\r\n");
      out.write("\t\t\t<div class=\"mb-3 mt-3\">\r\n");
      out.write("\t\t\t\t<label>한글 기업명</label> <br> <label class=\"la2\" for=\"email\">*&nbsp;주식회사,\r\n");
      out.write("\t\t\t\t\t(주) 등의 표기 없이 입력해주세요</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"name\" placeholder=\"예) 기업명 \" name=\"comNm\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>사원 수</label> <input type=\"number\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"emp\" placeholder=\"사원 수를 입력해주세요.('명'은 생략)\" name=\"comCnt\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>홈페이지 주소</label> <input type=\"url\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"company\" placeholder=\"홈페이지 주소를 입력해주세요\" name=\"comHpg\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>평균 연봉</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"salary\" placeholder=\"평균 연봉을 입력해주세요.('만 원'은 생략)\" name=\"comSal\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>설립일</label> <input type=\"date\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"company-date\" placeholder=\"설립일을 입력해주세요.\" name=\"comDate\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>회사 한줄 소개</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"introdce\" placeholder=\"회사 한줄 소개를 입력해주세요.\" name=\"comIntro\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>회사 상세 소개</label> <br>\r\n");
      out.write("\t\t\t\t<textarea style=\"height: 200px; width: 100%;\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"introdce\" placeholder=\"회사 한줄 소개를 입력해주세요.\"\r\n");
      out.write("\t\t\t\t\tname=\"comDetail\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"dropdown mb-3\">\r\n");
      out.write("\t\t\t\t<label>직군</label> <br> <label class=\"la2\">*&nbsp;더 많은\r\n");
      out.write("\t\t\t\t\t사람이 회원님의 기업을 쉽게 찾을 수 있도록 산업 분야를 추가해주세요.</label> <br>\r\n");
      out.write("\t\t\t\t<div id=\"search-item\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"jgval\" type=\"text\"\tplaceholder=\"직군 검색\" disabled>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\"\tid=\"jgCodeNo\" type=\"text\" name=\"jgCodeNo\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"jobgroupbtn\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\">직군\r\n");
      out.write("\t\t\t\t\t선택</button>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 1</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 2</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" onClick=\"setValue(this)\" >개발 3</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3 zip\">\r\n");
      out.write("\t\t\t\t<label>우편번호</label>\r\n");
      out.write("\t\t\t\t<div class=\"zipInput\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control zip\" id=\"postCode\" disabled>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" onclick=\"proc();\" value=\"우편번호 검색\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>주소1</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"roadAddress\" disabled>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>주소2</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"detailAddress\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"cityCodeNo\"\r\n");
      out.write("\t\t\t\t\tname=\"cityCodeNo\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"provCodeNo\"\r\n");
      out.write("\t\t\t\t\tname=\"provCodeNo\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>사업자 등록 번호</label><br> <label class=\"la2\">*&nbsp;사업자\r\n");
      out.write("\t\t\t\t\t등록번호는 기업관리자만 볼 수 있습니다.</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tid=\"companynum\" placeholder=\"사업자 등록번호를 입력해주세요.\" name=\"companynum\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>기업 공식 이메일</label> <br> <label class=\"la2\">*&nbsp;기업\r\n");
      out.write("\t\t\t\t\t공식 도메인의 이메일(@회사명.com)을 입력해주세요.</label> <label class=\"la2\">*&nbsp;해당\r\n");
      out.write("\t\t\t\t\t이메일로 인증 메일을 보내드립니다. 인증 시 기업 회원으로 등록됩니다.</label> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"companyEmail\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"기업 공식 이메일을 입력해주세요.\" name=\"companyEmail\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label>문의 담당자</label><br> <label class=\"la2\">*&nbsp;기업\r\n");
      out.write("\t\t\t\t\t페이지를 처음 등록한 분이 문의 담당자로 지정됩니다.</label> <label class=\"la2\">*&nbsp;변경하려면\r\n");
      out.write("\t\t\t\t\t기업 등록 후 '기업 프로필>기업 정보'에서 변경 및 삭제해주세요.</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"officer\" placeholder=\"ex)Elon Reeve Musk\"\r\n");
      out.write("\t\t\t\t\tname=\"officer\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"memNo\" name=\"memNo\" value=\"");
      out.print( memNo );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn-center-box\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"cpn-btn\">등록</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
