/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-10-27 01:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainJsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.jobOpening.vo.JOCardVO;
import kr.or.ddit.jobOpening.service.JobOpeningServiceImpl;
import kr.or.ddit.jobOpening.service.IJobOpeningService;
import java.util.List;
import kr.or.ddit.company.vo.CompanyVO;
import kr.or.ddit.company.service.CompanyServiceImpl;
import kr.or.ddit.company.service.ICompanyService;
import kr.or.ddit.hr.vo.HRMyInfoVO;
import kr.or.ddit.hr.service.HRServiceImpl;
import kr.or.ddit.hr.service.IHRService;
import kr.or.ddit.member.service.MemberServiceImpl;
import kr.or.ddit.member.service.IMemberService;
import kr.or.ddit.member.vo.MemberVO;

public final class myPagePerson_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.member.service.IMemberService");
    _jspx_imports_classes.add("kr.or.ddit.hr.service.IHRService");
    _jspx_imports_classes.add("kr.or.ddit.member.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.member.service.MemberServiceImpl");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRMyInfoVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.service.HRServiceImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.company.vo.CompanyVO");
    _jspx_imports_classes.add("kr.or.ddit.company.service.ICompanyService");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.vo.JOCardVO");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.service.JobOpeningServiceImpl");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.service.IJobOpeningService");
    _jspx_imports_classes.add("kr.or.ddit.company.service.CompanyServiceImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write(" ");
 
  
MemberVO loginMember = session.getAttribute("memVO") == null?
             null : (MemberVO)session.getAttribute("memVO");
IMemberService memberService = MemberServiceImpl.getInstance();
int memNo = loginMember.getMemNo();

IHRService hrService = HRServiceImpl.getInstance();
int hrNo = hrService.getHrNo(memNo);	

HRMyInfoVO myInfoVO = hrService.selectMyInfo(memNo);
// HR Detail page visit count
int hrCnt = myInfoVO.getHrCnt();
	
ICompanyService comService = CompanyServiceImpl.getInstance();
List<CompanyVO>  folComList = comService.getFolCompany(hrNo);
List<CompanyVO> favComList = comService.getFavCompany(hrNo);

IJobOpeningService joService = JobOpeningServiceImpl.getInstance();
List<JOCardVO> clipList = joService.getClipByHR(hrNo);
List<JOCardVO> applyList = joService.getApplyByHR(hrNo);
  
  
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<title>Bootstrap Example</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/d3ee6ce800.js\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\">\n");
      out.write("\n");
      out.write("<script src=\"../js/myPagePerson.js\"></script>\n");
      out.write("\n");
      out.write("<!--캘린더 관련 태그   -->\n");
      out.write("<link href='../css/myCalendar.css' rel='stylesheet' />\n");
      out.write("<link href='../css/myCalendar.min.css' rel='stylesheet' />\n");
      out.write("<script src='../js/myCalendarLocales-all.js'></script>\n");
      out.write("<script src='../js/myCalendar.js'></script>\n");
      out.write("<script src='../js/myCalendar.min.js'></script>\n");
      out.write("<!-- 유료서비스관련 태그 -->\n");
      out.write("<script src=\"../js/prod.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write(" document.addEventListener('DOMContentLoaded', ()=> {\n");
      out.write("    \n");
      out.write("\t\n");
      out.write("\t \n");
      out.write("    const calendarEl = document.querySelector('#myCalendar');\n");
      out.write("       \n");
      out.write("    \n");
      out.write("\n");
      out.write(" /*    let memNo = 1; \n");
      out.write("     //화면 로딩 시 자동으로 mwmNo를 저장하도록 한다.\n");
      out.write("     \n");
      out.write("     \n");
      out.write("    let goInfoBtn = document.querySelector('#goInfoBtn');\n");
      out.write("     console.log(goInfoBtn);\n");
      out.write("     goInfoBtn.addEventListener('click',()=>{\n");
      out.write("   \t console.log('click');\n");
      out.write("   \t  $.ajax({\n");
      out.write("\t    \t\turl : '/CodePeople/HRMyInfo.do',\n");
      out.write("\t    \t\ttype : 'get',\n");
      out.write("\t    \t\tdata : {\"memNo\" :memNo},\n");
      out.write("\t    \t\tdataType : 'json',\n");
      out.write("\t    \t\tsuccess : function(res){\n");
      out.write("\t    \t\t\tconsole.log(res);\n");
      out.write("\t    \t\t},\n");
      out.write("\t    \t\terror : function(xhr){\n");
      out.write("\t    \t\t\talert(`status : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xhr.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\ntext : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xhr.statusText}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\n");
      out.write("\t    \t\t}\n");
      out.write("\t    \t})\n");
      out.write("     })\n");
      out.write("     */\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("        var calendar = new FullCalendar.Calendar(calendarEl, {\n");
      out.write("           headerToolbar: {\n");
      out.write("                left: 'prev,next today',\n");
      out.write("                center: 'title',\n");
      out.write("                right: 'dayGridMonth,timeGridWeek,timeGridDay'\n");
      out.write("              },   \n");
      out.write("          locale: 'ko',    \n");
      out.write("          editable: true,\n");
      out.write("          initialView: 'dayGridMonth',\n");
      out.write("          navLinks: true, // can click day/week names to navigate views\n");
      out.write("          selectable: true,\n");
      out.write("          selectMirror: true,\n");
      out.write("          select: function(arg) {\n");
      out.write("            var title = prompt('추가할 일정을 입력해주세요.');\n");
      out.write("            if (title) {\n");
      out.write("              calendar.addEvent({\n");
      out.write("                title: title,\n");
      out.write("                start: arg.start,\n");
      out.write("                end: arg.end,\n");
      out.write("                allDay: arg.allDay\n");
      out.write("              })\n");
      out.write("            }\n");
      out.write("            calendar.unselect()\n");
      out.write("          },\n");
      out.write("          eventClick: function(arg) {\n");
      out.write("            if (confirm('일정을 삭제하시겠습니까?')) {\n");
      out.write("              arg.event.remove()\n");
      out.write("            }\n");
      out.write("          },\n");
      out.write("          editable: true,\n");
      out.write("          dayMaxEvents: true, // allow \"more\" link when too many events\n");
      out.write("          events: [\n");
      out.write("            {\n");
      out.write("              title: 'All Day Event',\n");
      out.write("              start: '2020-09-01'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Long Event',\n");
      out.write("              start: '2020-09-07',\n");
      out.write("              end: '2020-09-10'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              groupId: 999,\n");
      out.write("              title: 'Repeating Event',\n");
      out.write("              start: '2020-09-09T16:00:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              groupId: 999,\n");
      out.write("              title: 'Repeating Event',\n");
      out.write("              start: '2020-09-16T16:00:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Conference',\n");
      out.write("              start: '2020-09-11',\n");
      out.write("              end: '2020-09-13'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Meeting',\n");
      out.write("              start: '2020-09-12T10:30:00',\n");
      out.write("              end: '2020-09-12T12:30:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Lunch',\n");
      out.write("              start: '2020-09-12T12:00:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Meeting',\n");
      out.write("              start: '2020-09-12T14:30:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Happy Hour',\n");
      out.write("              start: '2020-09-12T17:30:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Dinner',\n");
      out.write("              start: '2020-09-12T20:00:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Birthday Party',\n");
      out.write("              start: '2020-09-13T07:00:00'\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("              title: 'Click for Google',\n");
      out.write("              url: 'http://google.com/',\n");
      out.write("              start: '2020-09-28'\n");
      out.write("            }\n");
      out.write("          ]\n");
      out.write("          \n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        calendar.render();\n");
      out.write("        \n");
      out.write("        \n");
      out.write("     \n");
      out.write("      });\n");
      out.write("\n");
      out.write(" $(function () {\n");
      out.write("\t\t$(\".list-group .memInfo\").click(function (e) { \n");
      out.write("\t\t\tlet submenu = $(this).next(\"ul\");\n");
      out.write("\n");
      out.write("\t\t\tif (submenu.is(\":visible\")) {\n");
      out.write("\t\t\t\tsubmenu.slideUp();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tsubmenu.slideDown();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\n");
      out.write(" \n");
      out.write("      \n");
      out.write("  \n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t\t.list-group .memInfo {\n");
      out.write("\t\t\tcursor: pointer;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.list-group .infoList {\n");
      out.write("\t\t\tdisplay: none;\n");
      out.write("\t\t\tpadding: 0px;\n");
      out.write("\t\t}\n");
      out.write("\t\t.list-group .infoList li:hover{\n");
      out.write("\t\t\tfilter: brightness(95%); \n");
      out.write("\t\t}\n");
      out.write("\t\t.preRemain{\n");
      out.write("\t\t\tborder : 1px solid silver;\n");
      out.write("\t\t\tmargin-bottom : 14px;\n");
      out.write("\t\t\tborder-radius: 0.8em;\n");
      out.write("\t\t\ttext-align: center;\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 헤더 -->\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\t<!-- 헤더 메인 메뉴 바 -->\n");
      out.write("\t\t<div id=\"header-container\">\n");
      out.write("\t\t\t<!-- 좌측 메뉴 -->\n");
      out.write("\t\t\t<div id=\"header-left-menu\">\n");
      out.write("\t\t\t\t<!-- 로고 -->\n");
      out.write("\t\t\t\t<a href=\"/CodePeople/rehearsal/index.jsp\" id=\"logo\"><i class=\"fas fa-copyright\"\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 32px;\"></i></a>\n");
      out.write("\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t<!-- 통합 검색창 -->\n");
      out.write("\t\t\t\t<div id=\"search-box\">\n");
      out.write("\t\t\t\t\t<div id=\"search-item\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search item\" style=\"width: 15.3px; height: 19px;\">\n");
      out.write("\t\t\t\t\t\t</i> <input class=\"\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 19px; border: none; border-right: 0px; border-top: 0px; boder-left: 0px; boder-bottom: 0px;\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"통합검색\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 우측 메뉴 -->\n");
      out.write("\t\t\t<div id=\"header-right-menu\">\n");
      out.write("\t\t\t\t<!-- 메인 메뉴 링크 -->\n");
      out.write("\t\t\t\t<div id=\"header-link-box\">\n");
      out.write("\t\t\t\t <a class=\"header-link\" href=\"/CodePeople/MainHR.do\">인재</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/CompanyPagingList.do\">기업</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/mainJsp/mainJO.jsp\">채용</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/EachBoardPaging.do\">커뮤니티</a>\n");
      out.write("            <a class=\"header-link myPage\" href=\"/CodePeople/GoMyPage.do\">마이페이지</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t<!-- 로그인버튼 -->\n");
      out.write("\t\t\t\t<a href=\"/CodePeople/rehearsal/logout.jsp\"><button id=\"header-login-btn\" class=\"btn btn-primary btn-sm\">로그아웃</button></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 바디 -->\n");
      out.write("\t<div id=\"body\">\n");
      out.write("\t\t<div id=\"body-container\">\n");
      out.write("\t\t\t<!-- 마이페이지 좌측 메뉴바 -->\n");
      out.write("\t\t\t<div class=\"nav-left-bar nav-my\">\n");
      out.write("\t\t\t\t<div class=\"nav-sticky\">\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"/CodePeople/HRMyInfo.do?memNo=1\">인재정보</a>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#fav-company\">관심기업</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#fav-jo\">관심공고</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#apply-jo\">지원공고</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"#myCalendar\">캘린더</a></li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"#peoplePayment\">유료서비스</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link memInfo\">회원정보</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"infoList\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"/CodePeople/rehearsal/memUpdate.jsp\">회원정보수정</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"/CodePeople/rehearsal/memDelete.jsp\">회원탈퇴</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"/CodePeople/rehearsal/memCertification.html\">재직증명신청</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 바디 콘텐츠 -->\n");
      out.write("\t\t\t<div id=\"content\">\n");
      out.write("\t\t\t\t<!-- 마이페이지 -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"content-box search-result\" >\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-header\">내정보 열람</h4>\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(hrCnt );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-header\">인재 인기도</h4>\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(folComList.size() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-header\">채용 지원</h4>\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(applyList.size() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-header\">관심 기업</h4>\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(favComList.size() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- 관십기업 박스 -->\n");
      out.write("\t\t\t\t<div id=\"fav-company\" class=\"content-box search-result company\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">관심기업</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");

if (favComList.size()==0){

      out.write("\t\n");
      out.write("\t<p style=\"text-align: center;\">등록한 관심기업이 없습니다.</p>\n");
	
}else{
	for (int i = 0; i < favComList.size(); i++){
		CompanyVO favCom = favComList.get(i); 

      out.write("\n");
      out.write("\t\t\t\t\t<!-- 검색결과 카드 -->\n");
      out.write("\t\t\t\t\t<div class=\"card\" idx=\"");
      out.print(favCom.getComNo());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-left\">\n");
      out.write("\t\t\t\t\t\t<img src=\"/CodePeople/images/logo");
      out.print(i );
      out.write(".png\" alt=\"Card image\" style=\"width:64px; height: 64px;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/CodePeople/CompanyDetailList.do?comNo=");
      out.print(favCom.getComNo());
      out.write("\" class=\"card-link\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">");
      out.print(favCom.getComNm());
      out.write("</h4></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 별점 박스 스크립트로 구현필요 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-rating-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-rating-star\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 채우기는 자바스크립트로 -->\n");
      out.write("\t\t\t");
 
			if(favCom.getComRev()!=null){
				int comRevStar = Math.round(favCom.getComRev());	
				for (int j = 0; j < comRevStar; i++) {
			
      out.write("\n");
      out.write("\t\t\t<span>★</span>\n");
      out.write("\t\t\t");
 
				}for (int j = comRevStar; j < 5; i++) { 
			
      out.write("\n");
      out.write("\t\t\t<span>☆</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-rating-text\">(");
      out.print(comRevStar );
      out.write(")</div>\n");
      out.write("\t\t\t");
 
				} 
			}else{
			
      out.write("\n");
      out.write("\t\t\t<span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-rating-text\">정보없음</div>\n");
      out.write("\t\t\t");
	
			}
			
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 기업정보 이동링크 -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/CodePeople/CompanyDetailList.do?comNo=");
      out.print(favCom.getComNo());
      out.write("#review\" class=\"card-link\">리뷰</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/CodePeople/CompanyDetailList.do?comNo=");
      out.print(favCom.getComNo());
      out.write("#board\" class=\"card-link\">게시물</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/CodePeople/CompanyDetailList.do?comNo=");
      out.print(favCom.getComNo());
      out.write("#salary\" class=\"card-link\">연봉</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/CodePeople/CompanyDetailList.do?comNo=");
      out.print(favCom.getComNo());
      out.write("#hr\" class=\"card-link\">채용</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");

	}
}

      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 관심공고 박스 -->\n");
      out.write("\t\t\t\t<div id=\"fav-jo\" class=\"content-box search-result jo\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">관심공고</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");

if(clipList.size()==0){

      out.write("\n");
      out.write("\t<p style=\"text-align: center;\">스크랩한 공고가 없습니다.</p>\n");

}else{
	for(int i = 0; i<clipList.size(); i++){
		JOCardVO clip = clipList.get(i);    
      String comSal = "";
      if (clip.getJoSal()==0){
    	  comSal="정보없음";
      }else if(clip.getJoSal()<=2000){
    	  comSal="0-2000만원";
      }else if(clip.getJoSal()<=2500){
    	  comSal="2000-2500만원";
      }else if(clip.getJoSal()<=3000){
    	  comSal="2500-3000만원";
      }else if(clip.getJoSal()<=4000){
    	  comSal="3000-4000만원";
      }else if(clip.getJoSal()<=5000){
    	  comSal="4000-5000만원";
      }else{
    	  comSal="5000만원 이상";
      }
 	  String rank ="";
 	  if(i%2==0){
 		  rank="경력";
 	  }else{
 		 rank="신입";
 	  }
 	
 			  

      out.write("\t\t\n");
      out.write("\t\t\t\t\t<!-- 검색결과 카드 -->\n");
      out.write("\t\t\t\t\t<div class=\"card card-jo\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-left\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/CodePeople/images/logo");
      out.print(i );
      out.write(".png\" alt=\"Card image\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 64px; height: 64px;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/CodePeople/JOCardDetil.do?joNo=");
      out.print(clip.getJoNo());
      out.write("\"><h4 class=\"card-title\">");
      out.print(clip.getJoTitle() );
      out.write("</h4></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 회사 소개, 직군 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-intro\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-intor\">");
      out.print(clip.getComIntro() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-jobgroup\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-jobgroup\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 채용공고 박스 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"jobs-detail-top\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\"><span class=\"jo-title\">");
      out.print(clip.getComNm() );
      out.write("</span></a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-salary jo-sm-font\">");
      out.print(comSal );
      out.write("</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-sm-font\">/</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-career jo-sm-font\">");
      out.print(rank );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t                   <span class=\"card-text jo-sm-font\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>&nbsp;&nbsp;\n");
      out.write("                        <span class=\"jo-start jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i>\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                            &nbsp;<span class=\"jo-start jo-sm-font\">~</span>&nbsp;\n");
      out.write("                        <span class=\"jo-end jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i> \n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\t\t\n");
		
	}

      out.write('\n');
	
}

      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 지원 공고 박스 -->\n");
      out.write("\t\t\t\t<div id=\"apply-jo\" class=\"content-box search-result jo\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">지원공고</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");

if(applyList.size()==0){

      out.write("\n");
      out.write("\t<p style=\"text-align: center;\">지원한 공고가 없습니다.</p>\n");

}else{
	for(int i = 0; i<applyList.size(); i++){
		JOCardVO clip = applyList.get(i);    
      String comSal = "";
      if (clip.getJoSal()==0){
    	  comSal="정보없음";
      }else if(clip.getJoSal()<=2000){
    	  comSal="0-2000만원";
      }else if(clip.getJoSal()<=2500){
    	  comSal="2000-2500만원";
      }else if(clip.getJoSal()<=3000){
    	  comSal="2500-3000만원";
      }else if(clip.getJoSal()<=4000){
    	  comSal="3000-4000만원";
      }else if(clip.getJoSal()<=5000){
    	  comSal="4000-5000만원";
      }else{
    	  comSal="5000만원 이상";
      }
 	  String rank ="";
 	  if(i%2==0){
 		  rank="경력";
 	  }else{
 		 rank="신입";
 	  }
 	
 			  

      out.write("\t\t\n");
      out.write("\t\t\t\t\t<!-- 검색결과 카드 -->\n");
      out.write("\t\t\t\t\t<div class=\"card card-jo\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-left\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/CodePeople/images/logo");
      out.print(i );
      out.write(".png\" alt=\"Card image\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 64px; height: 64px;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/CodePeople/JOCardDetil.do?joNo=");
      out.print(clip.getJoNo());
      out.write("\"><h4 class=\"card-title\">");
      out.print(clip.getJoTitle() );
      out.write("</h4></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 회사 소개, 직군 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-intro\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-intor\">");
      out.print(clip.getComIntro() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-jobgroup\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-jobgroup\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 채용공고 박스 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"jobs-detail-top\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\"><span class=\"jo-title\">");
      out.print(clip.getComNm() );
      out.write("</span></a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-salary jo-sm-font\">");
      out.print(comSal );
      out.write("</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-sm-font\">/</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-career jo-sm-font\">");
      out.print(rank );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t                   <span class=\"card-text jo-sm-font\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>&nbsp;&nbsp;\n");
      out.write("                        <span class=\"jo-start jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i>\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                            &nbsp;<span class=\"jo-start jo-sm-font\">~</span>&nbsp;\n");
      out.write("                        <span class=\"jo-end jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i> \n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\t\t\n");
		
	}

      out.write('\n');
	
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div id=\"myCalendar\" class=\"content-box\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- 유료컨텐츠  -->\n");
      out.write("\t\t\t\t<div id=\"peoplePayment\" class=\"content-box  search-result payment-desc my-main-cv\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">유료서비스</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"payment-box content-box\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">인재 프리미엄 플랜</h4>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 프리미엄 소개-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"payment-top-text\">\n");
      out.write("\t\t\t\t\t\t\t\t인재 프리미엄 서비스를 통해 기업에서 인재를 검색할 때에 검색목록 상단에 표시하도록 합니다.<br>\n");
      out.write("\t\t\t\t\t\t\t\t대취업전쟁시대에서 돈을 지불해 다른사람들보다 먼저 취업하세요.\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right preRemain\">\n");
      out.write("\t\t\t\t\t\t <h4 class=\"card-title cv-title\">남은 프리미엄 기간 : 9999일</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"payment-content-box\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">1개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t째째하게 1개월만 <br> 쓰고 취업될거라고 <br> 생각하시는건 아니죠?\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>자신있으시면 이걸로 하시던가요 ^^;</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>29,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn1\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">3개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t조금 덜 째째하게 3개월 플랜으로 하시게요? <br> 6개월이랑 가격차이도 별로 안나는데?\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t손해보는 장사 <br> 하시는군요 ㅡㅡ;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>79,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn2\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">6개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">코드피플 강력추천</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>당신은 능력보다 돈을 조금만 더 써서 남들보다 더 좋은 환경으로 취업할수 있을겁니다.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>저희만 믿으세요</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>99,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn3\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>ㄴ\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!--  풋터-->\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div id=\"footer-container\"></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
