/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-10-27 01:53:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainJsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.hr.vo.HRMyInfoVO;
import kr.or.ddit.hr.vo.HRInfoVO;
import kr.or.ddit.jobOpening.service.JobOpeningServiceImpl;
import kr.or.ddit.jobOpening.service.IJobOpeningService;
import kr.or.ddit.jobOpening.vo.JOCardVO;
import kr.or.ddit.hr.vo.HRCardVO;
import java.util.List;
import kr.or.ddit.hr.service.HRServiceImpl;
import kr.or.ddit.hr.service.IHRService;
import kr.or.ddit.company.vo.CompanyVO;
import kr.or.ddit.company.service.CompanyServiceImpl;
import kr.or.ddit.company.service.ICompanyService;
import kr.or.ddit.cmm.util.SessionCheck;
import kr.or.ddit.member.vo.MemberVO;

public final class myPageCompany_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.hr.service.IHRService");
    _jspx_imports_classes.add("kr.or.ddit.member.vo.MemberVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRInfoVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRMyInfoVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.service.HRServiceImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.ddit.cmm.util.SessionCheck");
    _jspx_imports_classes.add("kr.or.ddit.company.vo.CompanyVO");
    _jspx_imports_classes.add("kr.or.ddit.company.service.ICompanyService");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.service.JobOpeningServiceImpl");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.service.IJobOpeningService");
    _jspx_imports_classes.add("kr.or.ddit.jobOpening.vo.JOCardVO");
    _jspx_imports_classes.add("kr.or.ddit.hr.vo.HRCardVO");
    _jspx_imports_classes.add("kr.or.ddit.company.service.CompanyServiceImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");



MemberVO loginMember = session.getAttribute("memVO") == null?
            null : (MemberVO)session.getAttribute("memVO");


    int memCode = loginMember.getMemCode();
	
    int comNo = SessionCheck.getComNo(session, request);
    
 	   
    
    
    IHRService hrService = HRServiceImpl.getInstance();
    List<HRCardVO> folHRList = hrService.getFolHR(comNo);
    List<HRCardVO> favHRList = hrService.getFavHR(comNo);
    
    IJobOpeningService joService = JobOpeningServiceImpl.getInstance();
    List<JOCardVO> clipList = joService.getClipByCom(comNo);
	List<JOCardVO> applyList = joService.getApplyByCom(comNo);
    
    ICompanyService comService = CompanyServiceImpl.getInstance();
    CompanyVO com = comService.getCompany(comNo);
  
    
    int applyCnt = 0;
    if(applyList.size()>0){	
    	 for(int i = 0; i<applyList.size(); i++){
 	 	 	JOCardVO jo = applyList.get(i);	
 	 	 	int joNo = jo.getJoNo();
 	 	 	List<HRMyInfoVO> hrList = hrService.selectApplyHRByJo(joNo);
 	 	 	for(int j = 0; j < hrList.size(); j++){
 	 	 		applyCnt++;
 	 	 	}  	
 	 	 	}
    }else{
    	applyCnt=0;
    }
    
    
    
    

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<title>Bootstrap Example</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/d3ee6ce800.js\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 유료서비스관련 태그 -->\n");
      out.write("<script src=\"../js/prod.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 회원정보관련 스크립트 -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function () {\n");
      out.write("\t$(\".list-group .memInfo\").click(function (e) { \n");
      out.write("\t\tlet submenu = $(this).next(\"ul\");\n");
      out.write("\n");
      out.write("\t\tif (submenu.is(\":visible\")) {\n");
      out.write("\t\t\tsubmenu.slideUp();\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tsubmenu.slideDown();\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("  .list-group .memInfo {\n");
      out.write("    cursor: pointer;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .list-group .infoList {\n");
      out.write("    display: none;\n");
      out.write("    padding: 0px;\n");
      out.write("  }\n");
      out.write("  .list-group .infoList li:hover{\n");
      out.write("    filter: brightness(95%); \n");
      out.write("  }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 헤더 -->\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\t<!-- 헤더 메인 메뉴 바 -->\n");
      out.write("\t\t<div id=\"header-container\">\n");
      out.write("\t\t\t<!-- 좌측 메뉴 -->\n");
      out.write("\t\t\t<div id=\"header-left-menu\">\n");
      out.write("\t\t\t\t<!-- 로고 -->\n");
      out.write("\t\t\t\t<a href=\"/CodePeople/rehearsal/home.html\" id=\"logo\"><i class=\"fas fa-copyright\"\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 32px;\"></i></a>\n");
      out.write("\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t<!-- 통합 검색창 -->\n");
      out.write("\t\t\t\t<div id=\"search-box\">\n");
      out.write("\t\t\t\t\t<div id=\"search-item\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search item\" style=\"width: 15.3px; height: 19px;\">\n");
      out.write("\t\t\t\t\t\t</i> <input class=\"\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 19px; border: none; border-right: 0px; border-top: 0px; boder-left: 0px; boder-bottom: 0px;\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"통합검색\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- 우측 메뉴 -->\n");
      out.write("\t\t\t<div id=\"header-right-menu\">\n");
      out.write("\t\t\t\t<!-- 메인 메뉴 링크 -->\n");
      out.write("\t\t\t\t<div id=\"header-link-box\">\n");
      out.write("\t\t\t\t <a class=\"header-link\" href=\"/CodePeople/MainHR.do\">인재</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/CompanyPagingList.do\">기업</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/mainJsp/mainJO.jsp\">채용</a>\n");
      out.write("            <a class=\"header-link\" href=\"/CodePeople/EachBoardPaging.do\">커뮤니티</a>\n");
      out.write("            <a class=\"header-link myPage\" href=\"/CodePeople/GoMyPage.do\">마이페이지</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t<!-- 로그인버튼 -->\n");
      out.write("\t\t\t\t<a href=\"/CodePeople/rehearsal/home.html\"><button id=\"header-login-btn\" class=\"btn btn-primary btn-sm\">로그아웃</button></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 바디 -->\n");
      out.write("\t<div id=\"body\">\n");
      out.write("\t\t<div id=\"body-container\">\n");
      out.write("\t\t\t<!-- 마이페이지 좌측 메뉴바 -->\n");
      out.write("\t\t\t<div class=\"nav-left-bar nav-my\">\n");
      out.write("\t\t\t\t<div class=\"nav-sticky\">\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"/CodePeople/mainJsp/companyInsert.jsp\">기업관리</a></li>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#my-jo\">공고관리</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#fav-hr\">관심인재</a></li>\t\t\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"#apply-hr\">지원인재</a></li>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"#peoplePayment\">유료서비스</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link memInfo\" href=\"#\">회원정보</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"infoList\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/CodePeople/rehearsal/memUpdate.jsp\">회원정보수정</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\"><a class=\"nav-link\" href=\"/CodePeople/rehearsal/memDelete.jsp\">회원탈퇴</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("      <div id=\"content\">\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \t<div class=\"content-box search-result\" >\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-header\">스크랩 공고수</h4>\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(clipList.size() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-header\">관심기업 인기도</h4>\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(folHRList.size() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-header\">채용지원 인원</h4>\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(applyCnt );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\" style=\"align-items: baseline;\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-header\">리뷰 평점</h4>\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:50px;\"></div>\n");
      out.write("\t\t\t\t\t\t");

						if (com.getComRev()==null){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">0</h5>\n");
      out.write("\t\t\t\t\t\t\t");
 
						} else{
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-text\" style=\"text-align: center;\">");
      out.print(com.getComRev() );
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 관심공고 박스 -->\n");
      out.write("\t\t\t\t<div id=\"my-jo\" class=\"content-box search-result jo\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">공고 관리</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");

if(clipList.size()==0){

      out.write("\n");
      out.write("\t<p style=\"text-align: center;\">등록한 채용 공고가 없습니다.</p>\n");

}else{
	for(int i = 0; i<clipList.size(); i++){
		JOCardVO clip = clipList.get(i);    
      String comSal = "";
      if (clip.getJoSal()==0){
    	  comSal="정보없음";
      }else if(clip.getJoSal()<=2000){
    	  comSal="0-2000만원";
      }else if(clip.getJoSal()<=2500){
    	  comSal="2000-2500만원";
      }else if(clip.getJoSal()<=3000){
    	  comSal="2500-3000만원";
      }else if(clip.getJoSal()<=4000){
    	  comSal="3000-4000만원";
      }else if(clip.getJoSal()<=5000){
    	  comSal="4000-5000만원";
      }else{
    	  comSal="5000만원 이상";
      }
 	  String rank ="";
 	  if(i%2==0){
 		  rank="경력";
 	  }else{
 		 rank="신입";
 	  }
 	
 			  

      out.write("\t\t\n");
      out.write("\t\t\t\t\t<!-- 검색결과 카드 -->\n");
      out.write("\t\t\t\t\t<div class=\"card card-jo\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-left\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/CodePeople/images/logo");
      out.print(i );
      out.write(".png\" alt=\"Card image\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 64px; height: 64px;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/CodePeople/JOCardDetil.do?joNo=");
      out.print(clip.getJoNo());
      out.write("\"><h4 class=\"card-title\">");
      out.print(clip.getJoTitle() );
      out.write("</h4></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 회사 소개, 직군 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-intro\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-intor\">");
      out.print(clip.getComIntro() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-text card-jobs-detail-company-jobgroup\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"company-jobgroup\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 카드의 채용공고 박스 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"jobs-detail-top\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jobs-detail\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\"><span class=\"jo-title\">");
      out.print(clip.getComNm() );
      out.write("</span></a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-salary jo-sm-font\">");
      out.print(comSal );
      out.write("</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-sm-font\">/</span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"jo-career jo-sm-font\">");
      out.print(rank );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t                   <span class=\"card-text jo-sm-font\">");
      out.print(clip.getJgCodeNm() );
      out.write("</span>&nbsp;&nbsp;\n");
      out.write("                        <span class=\"jo-start jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i>\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoSdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                            &nbsp;<span class=\"jo-start jo-sm-font\">~</span>&nbsp;\n");
      out.write("                        <span class=\"jo-end jo-sm-font\"><i class=\"far fa-calendar-alt\">&nbsp;</i> \n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(0, 4) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(4, 6) );
      out.write(".\n");
      out.write("                        ");
      out.print(clip.getJoEdate().substring(6) );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\t\t\n");
		
	}

      out.write('\n');
	
}

      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"fav-hr\" class=\"content-box search-result human\">\n");
      out.write("          <div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">관심인재</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");


if (favHRList.size()==0){

      out.write("\n");
      out.write("\t<p style=\"text-align: center;\">등록한 관심인재가 없습니다.</p>\n");
      out.write("\t\t\n");
 
}else{
	for(int i = 0 ; i < favHRList.size(); i++){
	HRCardVO favHR = favHRList.get(i);

      out.write("\t\t\n");
      out.write("\t <div class=\"card\">\n");
      out.write("              <!-- 카드의 이미지태그는 복사해서 사용할것 src alt값 변경 필-->\n");
      out.write("              <div class=\"card-left\">\n");
      out.write("                  <img src=\"../logo.jpeg\" alt=\"Card image\" style=\"width:64px; height: 64px;\">\n");
      out.write("              </div>\n");
      out.write("              <!-- 카드의 정보 -->\n");
      out.write("              <div class=\"card-body card-right\">\n");
      out.write("               \t\t <div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/CodePeople/HRDetail.do?hrNo=");
      out.print( favHR.getHrNo());
      out.write("\"><h4 class=\"card-title\">");
      out.print(favHR.getMemNm());
      out.write("</h4></a>\n");
      out.write("\t    \t\t\t      <!-- 카드의 인재정보 직무, 회사, 활용언어 -->\n");
      out.write("                \t\t</div>\n");
      out.write("                \t <div class=\"card-text\">\n");
      out.write("                  \t\t<span class=\"job-title\">");
      out.print(favHR.getJtCodeNm() );
      out.write("</span>\n");
      out.write("                 \t</div>\n");
      out.write("                 \t<a href=\"#\" class=\"job-current card-link\">");
      out.print(favHR.getHrCurrCom() );
      out.write("</a>\n");
      out.write("                 \t<div class=\"card-text\">\n");
      out.write("                   <span class=\"job-language\">");
      out.print(favHR.getPlCodeNm() );
      out.write("</span>\n");
      out.write("                 \t</div>\n");
      out.write("             </div>\n");
      out.write("         \t\t\n");
      out.write("         \t</div>\n");
      out.write("         \t\n");
      out.write("         \t\n");
	
	}	
}

      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("                      \n");
      out.write("                   \n");
      out.write("         \n");
      out.write("                   \n");
      out.write("                   \n");
      out.write("       \n");
      out.write("       <div id=\"apply-hr\" class=\"content-box  \">\n");
      out.write("          <div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">지원인재</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t  </div>\n");


if(applyList.size()==0){

      out.write("\n");
      out.write("\t<p style=\"text-align: center;\">귀사의 공고에 지원한 인재가 없습니다.</p>\n");
 
	
}else{
	 	 for(int i = 0; i<applyList.size(); i++){
	 	 	JOCardVO jo = applyList.get(i);	
	 	 	int joNo = jo.getJoNo();
	 	 	List<HRMyInfoVO> hrList = hrService.selectApplyHRByJo(joNo);

      out.write("\n");
      out.write("<div id=\"accordion\" >\n");
      out.write("\t    <div class=\"content-box\" style=\"display:flex; flex-direction: column;\">\n");
      out.write("\t     \t\t\t <div class=\"card-header\">\n");
      out.write("\t\t\t\t\t  \t<a class=\"btn title-btn\" data-bs-toggle=\"collapse\" href=\"#");
      out.print(i);
      out.write("\">\n");
      out.write("\t\t\t\t\t <label style=\"font-weight: bold;\">공고번호&nbsp;</label>&nbsp;&nbsp;:&nbsp;&nbsp;<span class=\"board-title\">");
      out.print(jo.getJoNo());
      out.write("</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<label style=\"font-weight: bold;\">채용직무&nbsp;</label>&nbsp;&nbsp;:&nbsp;&nbsp;<span class=\"board-title\">");
      out.print(jo.getJtCodeNm());
      out.write("</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<label style=\"font-weight: bold;\">활동분야&nbsp;</label>&nbsp;&nbsp;:&nbsp;&nbsp;<span class=\"board-title\">");
      out.print(jo.getPlCodeNm());
      out.write("</span>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t                 </div>\n");
      out.write("\t                        <div id=\"collapseOne\" class=\"collapse show\" data-bs-parent=\"#");
      out.print(i);
      out.write("\" >\n");
      out.write("\t   \t\t\t\t\t\n");
 
			if(hrList.size()==0){

      out.write("\n");
      out.write("\t\t\t\t\t \t \t<p style=\"text-align: center;\">해당공고에 지원한 인재가 없습니다.</p>\n");

		}else{
			for(int j = 0; j < hrList.size(); j++){
					 	 			
					 	 		 HRMyInfoVO	hr = hrList.get(j); 

      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\t\n");
      out.write("\t\t\t\t\t \t \t\t <a href=\"/CodePeople/HRDetail.do?hrNo=");
      out.print(hr.getHrNo());
      out.write("\"><span class=\"card-title\">");
      out.print(hr.getMemNm());
      out.write("</span></a><br>\n");
      out.write("\t\t\t\t\t             <label for=\"\">자기소개&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduCodeNm\" >");
      out.print(hr.getHrCmt());
      out.write("</span><br>\n");
      out.write("\t\t\t\t\t             <label for=\"\">직무&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduSchNm\" >");
      out.print(hr.getJtCodeNm());
      out.write("</span><br>\n");
      out.write("\t\t\t\t\t             <label for=\"\">희망연봉&nbsp;</label>:&nbsp;&nbsp;<span class=\"board-title eduMajor\" >");
      out.print(hr.getHrSal());
      out.write("</span><br> \t\t\t\n");
      out.write("\t\t\t\t\t \t\t\t</div> \t\n");
      out.write("\t\t\t\t\t \t\t\n");
      out.write("\t");
		
				}			 	 		
					 	 		
			}
					 	 		
	
      out.write("\t \t \t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("</div>\n");
      out.write("\t");

		 }

		}
	 
      out.write("\t\t \n");
      out.write(" </div>\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        \t\t<!-- 유료컨텐츠  -->\n");
      out.write("\t\t\t\t<div id=\"peoplePayment\" class=\"content-box  search-result payment-desc my-main-cv\">\n");
      out.write("\t\t\t\t\t<div class=\"my-box-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"my-box-header\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"h1\">유료서비스</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"payment-box content-box\">\n");
      out.write("\t\t\t\t\t\t<!-- 카드의 정보 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body card-right\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-top-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">기업 프리미엄 플랜</h4>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 프리미엄 소개-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"payment-top-text\">\n");
      out.write("\t\t\t\t\t\t\t\t인재가 공고를 검색할 때 상단에 표시하도록 합니다.<br>\n");
      out.write("\t\t\t\t\t\t\t\t인력난 전쟁시대에서 능력있는 인재들에게 먼저 다가가세요!\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"payment-content-box\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">1개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t째째하게 1개월만 <br> 쓰고 구인하실꺼라고 <br> 생각하시는건 아니죠?\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>자신있으시면 이걸로 하시던가요 ^^;</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>29,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn1\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">3개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t조금 덜 째째하게 3개월 플랜으로 하시게요? <br> 6개월이랑 가격차이도 별로 안나는데?\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t손해보는 장사 <br> 하시는군요 ㅡㅡ;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>79,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn2\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content-box planbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"mt-1\">6개월</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"mt-5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"plan-desc\">코드피플 강력추천</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>당신은 능력보다 돈을 조금만 더 써서 남들보다 더 좋은 인재를 찾을 수 있을겁니다.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>저희만 믿으세요</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>99,900원</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg\" id=\"btn3\">결제하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!--  풋터-->\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div id=\"footer-container\"></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
