SELECT A.BOARD_NO, B.USER_NAME, A.REG_DATE, A.TITLE, A.CONTENT     
FROM TB_JDBC_BOARD A, TB_JDBC_USER B    
WHERE --A.USER_ID = B.USER_ID          
--AND A.
BOARD_NO = 0;

select * from TB_JDBC_BOARD where BOARD_NO = 0;

SELECT A.BOARD_NO, A.REG_DATE, A.TITLE, A.CONTENT     
FROM TB_JDBC_BOARD A
WHERE a.BOARD_NO = 0;

INSERT INTO TB_JDBC_BOARD(BOARD_NO, TITLE, CONTENT, USER_ID, REG_DATE)   
VALUES((SELECT NVL(MAX(BOARD_NO) + 1,1) FROM TB_JDBC_BOARD), 'admin', 'admin123', 'admin', SYSDATE)