사용예)장바구니테이블에서 4월과 5월에 판매된 상품 중 4월만 판매된 상품의 상품번호, 상품명, 수량합계, 판매금액합계를 구하시오

SELECT B.PROD_ID, B.PROD_NAME--, SUM(A.CART_QTY), SUM(A.CART_QTY * B.PROD_PRICE)
  FROM CART A, PROD B
 WHERE A.CART_PROD = B.PROD_ID AND SUBSTR(A.CART_NO,1,6) = '200504'
 --GROUP BY B.PROD_ID, B.PROD_NAME
MINUS
SELECT B.PROD_ID, B.PROD_NAME--, SUM(A.CART_QTY), SUM(A.CART_QTY * B.PROD_PRICE)
  FROM CART A, PROD B
 WHERE A.CART_PROD = B.PROD_ID AND SUBSTR(A.CART_NO,1,6) = '200505'
 --GROUP BY B.PROD_ID, B.PROD_NAME
MINUS
SELECT B.PROD_ID, B.PROD_NAME--, SUM(A.CART_QTY), SUM(A.CART_QTY * B.PROD_PRICE)
  FROM CART A, PROD B
 WHERE A.CART_PROD = B.PROD_ID AND SUBSTR(A.CART_NO,1,6) = '200504'
 --GROUP BY B.PROD_ID, B.PROD_NAME

사용예)회원테이블에서 마일리지가 많은 회원부터 차례대로 순위(등수)를 부여하시오
      회원번호, 회원명, 마일리지, 등수

SELECT MEM_ID, MEM_NAME, MEM_MILEAGE, RANK() OVER(ORDER BY MEM_MILEAGE DESC)
  FROM MEMBER
  
사용예)회원테이블에서 마일리지가 많은 회원부터 차례대로 순위(등수)를 부여하고 상위 5명의
      회원번호, 회원명, 마일리지, 등수를 출력하시오
SELECT *
  FROM (SELECT MEM_ID, MEM_NAME, MEM_MILEAGE, RANK() OVER(ORDER BY MEM_MILEAGE DESC) AS RK
          FROM MEMBER)
 WHERE RK <= 5

사용예)장바구니 테이블에서 2005년 5월 구매금액이 많은 회원부터 순위를 부여하여        
      회원번호, 회원명, 구매금액, 순위를 출력하시오

SELECT B.MEM_ID, B.MEM_NAME, SUM(A.CART_QTY * C.PROD_PRICE), RANK() OVER(ORDER BY SUM(A.CART_QTY * C.PROD_PRICE) DESC)
  FROM CART A, MEMBER B, PROD C
 WHERE A.CART_MEMBER = B.MEM_ID AND A.CART_PROD = C.PROD_ID AND SUBSTR(A.CART_NO,1,6) = '200505'
 GROUP BY B.MEM_ID, B.MEM_NAME