--PRIMARY KEY CHANGE ON LODGE_BOARD
--BEFORE : BOD_NO, LOD_NO
--AFTER : BOD_NO, LOD_NO, BOD_TYPE
--2021.08.15
--LEE KWANGHYO

--COLUMN ADD ON LODGE_BOARD
--BOD_ACTIVE
--2021.08.15
--LEE KWANGHYO

--COLUMN ADD ON ROOM
--RO_ACTIVE
--2021.08.15
--LEE KWANGHYO

--TABLE ADD CITY
--2021.08.17
--LEE KWANGHYO

--TABLE ADD PROV
--2021.08.17
--LEE KWANGHYO
--AND ALL CONSISTANT CHANGES

CREATE TABLE CITY 
(
  CITY_CODE NUMBER 
, CITY_NM VARCHAR2(30) 
);

--ALTER TABLE CITY ADD PRIMARY KEY (CITY_CODE);

CREATE TABLE PROV 
(
  PROV_CODE NUMBER 
, CITY_CODE NUMBER
, PROV_NM VARCHAR2(200) 
);

--ALTER TABLE CITY ADD PRIMARY KEY (PROV_CODE, CITY_CODE);
--ALTER TABLE CART ADD CONSTRAINT FK_PROV_CITY FOREIGN KEY (CITY_CODE) REFERENCES CITY(CITY_CODE);


CREATE TABLE LODGE_CODE 
(
  LOD_CODE NUMBER -- NOT NULL
, LOD_CODE_NM VARCHAR2(30) -- NOT NULL
);

--ALTER TABLE LODGE_CODE ADD PRIMARY KEY (LOD_CODE);

CREATE TABLE LODGE 
(
  LOD_NO NUMBER     --  NOT NULL
, LOD_NM VARCHAR2(100)  --NOT NULL
, LOD_CODE NUMBER       --NOT NULL
--, LOD_ADD_CITY VARCHAR2(50)     --NOT NULL
--, LOD_ADD_PROV VARCHAR2(50)     --NOT NULL
, CITY_CODE NUMBER                -- CHANGE DATE 2021.08.17
, PROV_CODE NUMBER                -- CHANGE DATE 2021.08.17
, LOD_ADD_DETAIL VARCHAR2(200)  
, LOD_DETAIL VARCHAR2(200)      --NOT NULL
);

--ALTER TABLE LODGE ADD PRIMARY KEY (LOD_NO);
--ALTER TABLE LODGE ADD CONSTRAINT FK_LODGE_CODE FOREIGN KEY (LOD_CODE) REFERENCES LODGE_CODE(LOD_CODE);
--ALTER TABLE LODGE ADD CONSTRAINT FK_LODGE_PROV FOREIGN KEY (PROV_CODE, CITY_CODE) REFERENCES PROV(PROV_CODE, CITY_CODE);

CREATE TABLE MEMBER_CODE 
(
  MEM_CODE NUMBER           --NOT NULL
, MEM_CODE_NM VARCHAR2(30)  --NOT NULL
);

--ALTER TABLE MEMBER_CODE ADD PRIMARY KEY (MEM_CODE);

CREATE TABLE MEMBER 
(
  MEM_NO NUMBER     --NOT NULL
, MEM_ID VARCHAR2(30) 
, MEM_PW VARCHAR2(30) 
, MEM_NM VARCHAR2(30) --NOT NULL
, MEM_TEL VARCHAR2(100) --NOT NULL
, MEM_EMAIL VARCHAR2(100) 
, MEM_CODE NUMBER 
, MEM_ACTIVE NUMBER 
);

--ALTER TABLE MEMBER ADD PRIMARY KEY (MEM_NO);
--ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_CODE FOREIGN KEY (MEM_CODE) REFERENCES MEMBER_CODE(MEM_CODE);

CREATE TABLE OWNERSHIP 
(
  MEM_NO NUMBER --NOT NULL
, LOD_NO NUMBER --NOT NULL
);

--ALTER TABLE OWNERSHIP ADD PRIMARY KEY (MEM_NO, LOD_NO);
--ALTER TABLE OWNERSHIP ADD CONSTRAINT FK_OWNERSHIP_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);
--ALTER TABLE OWNERSHIP ADD CONSTRAINT FK_OWNERSHIP_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);


CREATE TABLE LODGE_BOARD 
(
  BOD_NO NUMBER         --NOT NULL
, LOD_NO NUMBER         --NOT NULL
, BOD_CODE NUMBER       --NOT NULL
, MEM_NO NUMBER         --NOT NULL
, BOD_TITLE VARCHAR2(200)   --NOT NULL
, BOD_CONTENT VARCHAR2(2000) --NOT NULL
, BOD_REG_DATE DATE 
, BOD_RATING NUMBER 
, BOD_ACTIVE NUMBER
);

--ALTER TABLE LODGE_BOARD ADD PRIMARY KEY (BOD_NO, LOD_NO, BOD_CODE);
--ALTER TABLE LODGE_BOARD ADD CONSTRAINT FK_BOARD_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);
--ALTER TABLE LODGE_BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);

CREATE TABLE ROOM_CODE 
(
  RO_CODE NUMBER --NOT NULL
, RO_CODE_NM VARCHAR2(30)   --NOT NULL
);

--ALTER TABLE ROOM_CODE ADD PRIMARY KEY (RO_CODE);

CREATE TABLE ROOM 
(
  RO_NO NUMBER --NOT NULL
, LOD_NO NUMBER --NOT NULL
, RO_ACTIVE NUMBER
, RO_MIN_CAP NUMBER 
, RO_MAX_CAP NUMBER 
, RO_N_PRICE NUMBER --NOT NULL
, RO_A_PRICE NUMBER --NOT NULL
, RO_CODE NUMBER    --NOT NULL
, RO_CIN VARCHAR(30)
, RO_COUT VARCHAR(30)
, RO_DETAIL VARCHAR2(500) 
);

--ALTER TABLE ROOM ADD PRIMARY KEY (RO_NO, LOD_NO);
--ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);
--ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_CODE FOREIGN KEY (RO_CODE) REFERENCES ROOM_CODE(RO_CODE);

CREATE TABLE TBL_ORDER 
(
  ORD_NO NUMBER --NOT NULL
, MEM_NO NUMBER --NOT NULL
, ORD_PRICE NUMBER 
, ORD_DATE DATE --NOT NULL
);

--ALTER TABLE TBL_ORDER ADD PRIMARY KEY (ORD_NO);
--ALTER TABLE TBL_ORDER ADD CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);

CREATE TABLE RESERVATION 
(
  RESV_NO NUMBER --NOT NULL
, ORD_NO NUMBER --NOT NULL
, LOD_NO NUMBER --NOT NULL
, RO_NO NUMBER --NOT NULL
, RESV_SDATE DATE --NOT NULL
, RESV_EDATE DATE --NOT NULL
, RESV_CODE NUMBER 
, RESV_CAP NUMBER --NOT NULL
, RESV_SUM NUMBER 
);

--ALTER TABLE RESERVATION ADD PRIMARY KEY (RESV_NO);
--ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_ORDER FOREIGN KEY (ORD_NO) REFERENCES TBL_ORDER(ORD_NO);
--ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);

CREATE TABLE ROOM_HISTORY 
(
  RO_NO NUMBER --NOT NULL
, LOD_NO NUMBER --NOT NULL
, RO_UPDATE DATE --NOT NULL
, RO_N_PRICE NUMBER --NOT NULL
, RO_A_PRICE NUMBER --NOT NULL
);

--ALTER TABLE ROOM_HISTORY ADD PRIMARY KEY (RO_NO, LOD_NO, RO_UPDATE);
--ALTER TABLE ROOM_HISTORY ADD CONSTRAINT FK_HISTORY_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);

CREATE TABLE RESERVATION_HISTORY 
(
  RESH_NO NUMBER --NOT NULL
, RESH_UPDATE DATE --NOT NULL
, RESV_NO NUMBER --NOT NULL
, ORD_NO NUMBER--NOT NULL
, LOD_NO NUMBER --NOT NULL
, RO_NO NUMBER --NOT NULL
, RESV_SDATE DATE --NOT NULL
, RESV_EDATE DATE --NOT NULL
, RESV_CODE NUMBER --NOT NULL
, RESV_CAP NUMBER --NOT NULL
, RESV_SUM NUMBER 
, ORD_DATE DATE --NOT NULL
);

--ALTER TABLE RESERVATION_HISTORY ADD PRIMARY KEY (RESH_NO, RESH_UPDATE);
--ALTER TABLE RESERVATION_HISTORY ADD CONSTRAINT FK_HISTORY_RESERVATION FOREIGN KEY (RESV_NO) REFERENCES RESERVATION(RESV_NO);
--ALTER TABLE RESERVATION_HISTORY ADD CONSTRAINT FK_RESH_ORDER FOREIGN KEY (ORD_NO) REFERENCES TBL_ORDER(ORD_NO);

--CREATE TABLE CART 
--(
--  CART_NO NUMBER 
--, MEM_NO NUMBER 
--, RO_NO NUMBER 
--, LOD_NO NUMBER 
--, RO_PRICE NUMBER 
--, RESV_SDATE DATE 
--, RESV_EDATE DATE 
--, RESV_SUM NUMBER 
--, RESV_CAP NUMBER 
--);

--ALTER TABLE CART ADD PRIMARY KEY (CART_NO);
--ALTER TABLE CART ADD CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);
--ALTER TABLE CART ADD CONSTRAINT FK_CART_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);


DROP TABLE LODGE_BOARD;
DROP TABLE RESERVATION_HISTORY;
DROP TABLE ROOM_HISTORY;
--DROP TABLE CART;
DROP TABLE OWNERSHIP;
DROP TABLE RESERVATION;
DROP TABLE TBL_ORDER;
DROP TABLE ROOM;
DROP TABLE LODGE;
DROP TABLE MEMBER;
DROP TABLE LODGE_CODE;
DROP TABLE MEMBER_CODE;
DROP TABLE ROOM_CODE;
DROP TABLE PROV;
DROP TABLE CITY;