CREATE TABLE LODGE_CODE 
(
  LOD_CODE NUMBER 
, LOD_NM VARCHAR2(30) 
);

--ALTER TABLE LODGE_CODE ADD PRIMARY KEY (LOD_CODE);

CREATE TABLE LODGE 
(
  LOD_NO NUMBER 
, LOD_CODE NUMBER 
, LOD_NM VARCHAR2(100) 
, LOD_ADD_CITY VARCHAR2(50) 
, LOD_ADD_PROV VARCHAR2(50) 
, LOD_ADD_DETAIL VARCHAR2(200) 
, LOD_DETAIL VARCHAR2(200) 
);

--ALTER TABLE LODGE ADD PRIMARY KEY (LOD_NO);
--ALTER TABLE LODGE ADD CONSTRAINT FK_LODGE_CODE FOREIGN KEY (LOD_CODE) REFERENCES LODGE_CODE(LOD_CODE);

CREATE TABLE MEMBER 
(
  MEM_NO NUMBER 
, MEM_ID VARCHAR2(30) 
, MEM_PW VARCHAR2(30) 
, MEM_NM VARCHAR2(30) 
, MEM_TEL VARCHAR2(100) 
, MEM_EMAIL VARCHAR2(100) 
, MEM_CODE NUMBER 
, MEM_ACTIVE NUMBER 
);

--ALTER TABLE MEMBER ADD PRIMARY KEY (MEM_NO);

CREATE TABLE OWNERSHIP 
(
  MEM_NO NUMBER 
, LOD_NO NUMBER 
);

--ALTER TABLE OWNERSHIP ADD PRIMARY KEY (MEM_NO, LOD_NO);
--ALTER TABLE OWNERSHIP ADD CONSTRAINT FK_OWNERSHIP_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);
--ALTER TABLE OWNERSHIP ADD CONSTRAINT FK_OWNERSHIP_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);


CREATE TABLE LODGE_BOARD 
(
  BOD_NO NUMBER 
, LOD_NO NUMBER 
, MEM_NO NUMBER 
, BOD_TITLE VARCHAR2(200) 
, BOD_CONTENT VARCHAR2(2000) 
, BOD_REG_DATE DATE 
, BOD_RATING NUMBER 
, BOD_CODE NUMBER 
);

--ALTER TABLE LODGE_BOARD ADD PRIMARY KEY (BOD_NO, LOD_NO);
--ALTER TABLE LODGE_BOARD ADD CONSTRAINT FK_BOARD_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);
--ALTER TABLE LODGE_BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);

CREATE TABLE ROOM 
(
  RO_NO NUMBER 
, LOD_NO NUMBER 
, RO_MIN_CAP NUMBER 
, RO_MAX_CAP NUMBER 
, RO_PRICE NUMBER 
, RO_AVAL NUMBER 
, RO_GRADE NUMBER 
, RO_CIN TIMESTAMP 
, RO_COUT TIMESTAMP 
, RO_DETAIL VARCHAR2(500) 
);

--ALTER TABLE ROOM ADD PRIMARY KEY (RO_NO, LOD_NO);
--ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_LODGE FOREIGN KEY (LOD_NO) REFERENCES LODGE(LOD_NO);

CREATE TABLE RESERVATION 
(
  RESV_NO NUMBER 
, MEM_NO NUMBER 
, LOD_NO NUMBER 
, RO_NO NUMBER 
, RESV_SDATE DATE 
, RESV_EDATE DATE 
, RESV_CODE NUMBER 
, RESV_CAP NUMBER 
, RESV_SUM NUMBER 
, RESV_DATE DATE 
);

--ALTER TABLE RESERVATION ADD PRIMARY KEY (RESV_NO);
--ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);
--ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);

CREATE TABLE ROOM_HISTORY 
(
  RO_NO NUMBER 
, LOD_NO NUMBER 
, RO_UPDATE DATE 
, RO_PRICE NUMBER 
);

--ALTER TABLE ROOM_HISTORY ADD PRIMARY KEY (RO_NO, LOD_NO, RO_UPDATE);
--ALTER TABLE ROOM_HISTORY ADD CONSTRAINT FK_HISTORY_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);

CREATE TABLE RESERVATION_HISTORY 
(
  RESH_NO NUMBER 
, RESH_UPDATE DATE 
, RESV_NO NUMBER 
, RESV_SDATE DATE 
, RESV_EDATE DATE 
, RESV_CODE NUMBER 
, MEM_NO NUMBER 
, LOD_NO NUMBER 
, RO_NO NUMBER 
, RESV_DATE DATE 
, RESV_CAP NUMBER 
, RESV_SUM NUMBER 
);

--ALTER TABLE RESERVATION_HISTORY ADD PRIMARY KEY (RESH_NO, RESH_UPDATE);
--ALTER TABLE RESERVATION_HISTORY ADD CONSTRAINT FK_HISTORY_RESERVATION FOREIGN KEY (RESV_NO) REFERENCES RESERVATION(RESV_NO);

CREATE TABLE CART 
(
  CART_NO NUMBER 
, MEM_NO NUMBER 
, RO_NO NUMBER 
, LOD_NO NUMBER 
, RO_PRICE NUMBER 
, RESV_SDATE DATE 
, RESV_EDATE DATE 
, RESV_SUM NUMBER 
, RESV_CAP NUMBER 
);

--ALTER TABLE CART ADD PRIMARY KEY (CART_NO);
--ALTER TABLE CART ADD CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO);
--ALTER TABLE CART ADD CONSTRAINT FK_CART_ROOM FOREIGN KEY (RO_NO, LOD_NO) REFERENCES ROOM(RO_NO, LOD_NO);

DROP TABLE LODGE_BOARD;
DROP TABLE RESERVATION_HISTORY;
DROP TABLE ROOM_HISTORY;
DROP TABLE CART;
DROP TABLE OWNERSHIP;
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE LODGE;
DROP TABLE MEMBER;
DROP TABLE LODGE_CODE;
